// Flo·zēk Data File — Complete Edition
// 55 brands · 120+ cities · Filter guide · Civic contacts · Glossary · Walter Q&A

export const UMBRELLA_COMPANIES = {
  "Gerolsteiner": "Gerolsteiner Brunnen GmbH (Independent)",
  "San Pellegrino": "Nestlé S.A.",
  "Perrier": "Nestlé S.A.",
  "Evian": "Danone S.A.",
  "Contrex": "Danone S.A.",
  "Apollinaris": "Refresco Group",
  "Badoit": "Danone S.A.",
  "Hildon": "Hildon Ltd (Independent)",
  "Mountain Valley": "BlueTriton Brands",
  "Acqua Panna": "Nestlé S.A.",
  "Fiji": "The Wonderful Company",
  "Voss": "Reignwood Group",
  "Icelandic Glacial": "Icelandic Glacial (Independent)",
  "Topo Chico": "The Coca-Cola Company",
  "Waiakea": "Waiakea Inc (Independent)",
  "Poland Spring": "BlueTriton Brands",
  "Deer Park": "BlueTriton Brands",
  "Arrowhead": "BlueTriton Brands",
  "Zephyrhills": "BlueTriton Brands",
  "Smartwater": "The Coca-Cola Company",
  "Essentia": "Nestlé S.A.",
  "Eternal": "Eternal Water (Independent)",
  "Core Hydration": "Keurig Dr Pepper",
  "Liquid Death": "Liquid Death Mountain Water Inc",
  "Flow Alkaline": "Flow Beverage Corp",
  "Just Water": "Just Goods Inc",
  "LaCroix": "National Beverage Corp",
  "Pure Life": "BlueTriton Brands",
  "Dasani": "The Coca-Cola Company",
  "Aquafina": "PepsiCo Inc",
  "Great Value": "Walmart Inc",
  "Kirkland Still": "Costco Wholesale Corp",
  "Crystal Geyser": "CG Roxane LLC (Independent)",
  "Dollar Tree Spring": "Dollar Tree Inc",
  "Kirkland Sparkling": "Costco Wholesale Corp",
  "Aldi Aqua D'or": "ALDI Group",
  "Members Mark": "Sams Club / Walmart Inc",
  "Niagara": "Niagara Bottling LLC (Independent)",
  "Target GoodGather": "Target Corporation",
  "Proud Source": "Proud Source Water Inc (Independent)",
  "DG Drinking Water": "Dollar General Corp",
  "365 Whole Foods": "Amazon / Whole Foods Market",
  "Trader Joes": "Trader Joes / Aldi Group",
  "Publix Water": "Publix Super Markets Inc",
  "Kroger Water": "The Kroger Co",
  "CVS Water": "CVS Health Corp",
  "Walgreens Water": "Walgreens Boots Alliance",
  "Wegmans Water": "Wegmans Food Markets (Independent)",
  "HEB Water": "HEB Grocery Co (Independent)",
  "Wawa Water": "Wawa Inc (Independent)",
  "Sparkling Ice": "Talking Rain Beverage Co",
  "Bodyarmor Water": "The Coca-Cola Company",
  "Prime Hydration": "Prime Hydration LLC / Logan Paul KSI",
  "Liquid IV": "Unilever PLC",
  "Propel": "PepsiCo Inc",
};

export const WATER_DB = [
  {
    id:1, name:"Gerolsteiner", tier:"premium", logo:"🇩🇪", pH:5.9,
    calcium:348, magnesium:108, sodium:118, tds:2527, bicarbonate:1816,
    price:1.90, plastic:false, type:"Natural Sparkling", origin:"Volcanic Eifel, Germany",
    verdict:"Most mineral-dense water on earth. Extraordinary Mg and Ca. Clinically superior for deficiency correction.",
    pros:["Highest calcium and magnesium of any mainstream brand","Bicarbonate buffer excellent for digestion","Glass bottle — zero plastic leaching","WHO mineral standards exceeded by 3x"],
    cons:["Very high TDS may cause scaling in some people","Carbonation not suitable for all digestive conditions","Premium price point","Heavy to ship — high carbon footprint"],
    filterNote:"Not applicable — premium mineral water. No filtration needed.",
    bestFor:"Mineral deficiency correction, calcium and magnesium supplementation, digestive health",
    avoid:"Anyone managing kidney stones or high TDS sensitivity"
  },
  {
    id:2, name:"San Pellegrino", tier:"premium", logo:"🇮🇹", pH:7.7,
    calcium:174, magnesium:56, sodium:36, tds:1109, bicarbonate:243,
    price:2.30, plastic:false, type:"Natural Sparkling", origin:"Bergamo Alps, Italy",
    verdict:"Gold standard sparkling mineral water. Outstanding Ca and Mg. High sulfate aids digestion.",
    pros:["Outstanding calcium and magnesium balance","Naturally alkaline pH 7.7","Glass bottle option available","Sulfate content aids fat digestion"],
    cons:["Owned by Nestlé — corporate water extraction concerns","High price per liter","Carbonation may cause bloating","Sodium moderate at 36 mg/L"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Dinner table water, digestive health, mineral supplementation",
    avoid:"Those sensitive to carbonation"
  },
  {
    id:3, name:"Perrier", tier:"premium", logo:"🫧", pH:5.5,
    calcium:155, magnesium:3, sodium:9, tds:475, bicarbonate:390,
    price:2.10, plastic:false, type:"Natural Sparkling", origin:"Vergeze, France",
    verdict:"Highest calcium of any mainstream sparkling. Low Mg is a gap. Excellent boost not sole water.",
    pros:["Highest calcium of any sparkling brand at 155 mg/L","Very low sodium","Glass bottle","Strong brand recognition worldwide"],
    cons:["Magnesium only 3 mg/L — significant gap","Acidic pH 5.5 from carbonation","Owned by Nestlé","Not suitable as sole daily water"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Calcium boost, cocktail mixer, occasional sparkling",
    avoid:"Do not use as sole water source due to low magnesium"
  },
  {
    id:4, name:"Evian", tier:"premium", logo:"🏔️", pH:7.2,
    calcium:80, magnesium:26, sodium:6, tds:309, bicarbonate:357,
    price:2.50, plastic:true, type:"Natural Still", origin:"French Alps, France",
    verdict:"One of the most mineral-balanced waters in the world. Excellent Mg. The benchmark for still mineral water.",
    pros:["Perfect mineral balance — Ca and Mg ratio ideal","Naturally alkaline pH 7.2","Neutral sodium at 6 mg/L","High bicarbonate buffer 357 mg/L"],
    cons:["Owned by Danone — corporate water concerns","Plastic bottle standard packaging","High price","Long shipping distance from France"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Daily premium drinking water, pregnancy hydration, children",
    avoid:"Budget-conscious consumers — better value options exist"
  },
  {
    id:5, name:"Contrex", tier:"premium", logo:"💪", pH:7.4,
    calcium:486, magnesium:84, sodium:9, tds:2078, bicarbonate:403,
    price:1.80, plastic:true, type:"Natural Still", origin:"Contrexeville, France",
    verdict:"Highest calcium of any still water 486 mg/L. Exceptional for bone health deficiency correction.",
    pros:["Highest calcium of any still water in database","Strong magnesium at 84 mg/L","Very low sodium","Historically marketed for weight management"],
    cons:["Extremely high TDS — rotate with lower TDS water","Not suitable as sole daily water","Owned by Danone","Plastic bottle"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Bone health, calcium deficiency, post-menopause women",
    avoid:"Do not drink exclusively — rotate with lower TDS water"
  },
  {
    id:6, name:"Apollinaris", tier:"premium", logo:"👑", pH:5.9,
    calcium:89, magnesium:130, sodium:410, tds:2500, bicarbonate:1820,
    price:2.10, plastic:false, type:"Natural Sparkling", origin:"Bad Neuenahr, Germany",
    verdict:"Highest magnesium in database 130 mg/L. Very high sodium. Use in rotation for Mg supplementation.",
    pros:["Highest magnesium of any brand at 130 mg/L","Outstanding bicarbonate buffer","Glass bottle","Excellent for magnesium deficiency"],
    cons:["Sodium 410 mg/L — very high — avoid if managing blood pressure","Acidic pH from carbonation","Not suitable as sole water","Limited US availability"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Magnesium deficiency, muscle cramps, poor sleep correction",
    avoid:"Anyone managing hypertension or sodium restriction"
  },
  {
    id:7, name:"Badoit", tier:"premium", logo:"🇫🇷", pH:6.0,
    calcium:190, magnesium:85, sodium:150, tds:1200, bicarbonate:1300,
    price:2.40, plastic:false, type:"Natural Sparkling", origin:"Saint-Galmier, France",
    verdict:"Outstanding Ca and Mg balance. High sodium is a consideration. Among the best mineral waters globally.",
    pros:["Exceptional calcium and magnesium balance","Very high bicarbonate buffer","Glass bottle","Naturally lightly sparkling"],
    cons:["Sodium 150 mg/L — elevated","Owned by Danone","Limited US availability","Premium price"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Digestive health, mineral supplementation, food pairing",
    avoid:"Sodium-restricted diets"
  },
  {
    id:8, name:"Hildon", tier:"premium", logo:"🏰", pH:7.4,
    calcium:98, magnesium:5, sodium:11, tds:312, bicarbonate:288,
    price:2.20, plastic:false, type:"Natural Still", origin:"Hampshire, England",
    verdict:"High calcium naturally balanced. Preferred water of the British royal household.",
    pros:["Preferred water of the British royal family","High calcium at 98 mg/L","Very low sodium","Glass bottle — premium presentation"],
    cons:["Magnesium only 5 mg/L — very low","Limited US distribution","Higher price","Independent brand — limited scale"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Calcium supplementation, formal dining, gifting",
    avoid:"Those needing magnesium supplementation"
  },
  {
    id:9, name:"Mountain Valley", tier:"premium", logo:"⛰️", pH:7.8,
    calcium:68, magnesium:22, sodium:3, tds:220, bicarbonate:272,
    price:2.60, plastic:false, type:"Natural Still", origin:"Ouachita Mountains, AR",
    verdict:"One of Americas finest spring waters. Served at the US Senate. Excellent Ca and Mg balance.",
    pros:["Served at US Senate since 1888","Naturally alkaline pH 7.8","Glass bottle","Lowest sodium of any premium brand at 3 mg/L"],
    cons:["Owned by BlueTriton — same parent as Poland Spring","Premium price","Limited retail availability","Lower minerals than European premium brands"],
    filterNote:"Not applicable — premium spring water.",
    bestFor:"Daily premium still water, low sodium diets, American heritage",
    avoid:"Those seeking highest mineral content — European brands exceed it"
  },
  {
    id:10, name:"Acqua Panna", tier:"premium", logo:"🌿", pH:8.0,
    calcium:34, magnesium:7, sodium:6, tds:122, bicarbonate:107,
    price:2.10, plastic:false, type:"Natural Still", origin:"Tuscany, Italy",
    verdict:"Beautifully balanced naturally alkaline Tuscan water. Perfect food pairing.",
    pros:["Naturally alkaline pH 8.0","Low TDS — very smooth taste","Excellent food pairing water","Glass bottle option"],
    cons:["Low minerals — calcium only 34 mg/L","Owned by Nestlé","Magnesium only 7 mg/L","Not ideal as sole mineral source"],
    filterNote:"Not applicable — premium mineral water.",
    bestFor:"Restaurant table water, food pairing, smooth taste preference",
    avoid:"Those needing significant mineral supplementation"
  },
  {
    id:11, name:"Fiji", tier:"premium", logo:"🏝️", pH:7.7,
    calcium:18, magnesium:15, sodium:18, tds:222, bicarbonate:152,
    price:2.20, plastic:true, type:"Artesian Still", origin:"Viti Levu, Fiji Islands",
    verdict:"Silica-rich artesian with good pH. Modest minerals despite premium marketing.",
    pros:["High silica content — good for skin and hair","Naturally alkaline pH 7.7","Artesian aquifer source","Strong brand recognition"],
    cons:["Calcium only 18 mg/L — low for price","Owned by The Wonderful Company — billionaire-owned","Plastic bottle — long shipping from Fiji","Premium price for modest mineral content"],
    filterNote:"Not applicable — artesian spring water.",
    bestFor:"Silica intake, skin health, brand prestige",
    avoid:"Those prioritizing calcium and magnesium — better options at lower price"
  },
  {
    id:12, name:"Voss", tier:"premium", logo:"🇳🇴", pH:6.0,
    calcium:5, magnesium:1, sodium:6, tds:22, bicarbonate:17,
    price:3.50, plastic:false, type:"Natural Still", origin:"Iveland, Norway",
    verdict:"Beautiful bottle virtually zero mineral content. Most overpriced mineral-poor water available.",
    pros:["Iconic minimalist bottle design","Very low TDS — ultra clean taste","Low sodium","Norwegian glacial source"],
    cons:["Calcium only 5 mg/L — essentially zero minerals","Magnesium only 1 mg/L","Most expensive water for worst mineral value","Acidic pH 6.0","Owned by Chinese Reignwood Group"],
    filterNote:"Not applicable — but consider adding mineral drops to improve nutritional value.",
    bestFor:"Gifting, aesthetic presentation, mineral-sensitive individuals",
    avoid:"Anyone seeking mineral benefit — worst value in database"
  },
  {
    id:13, name:"Icelandic Glacial", tier:"premium", logo:"🧊", pH:8.4,
    calcium:3, magnesium:1, sodium:7, tds:62, bicarbonate:87,
    price:2.80, plastic:false, type:"Natural Still", origin:"Olfus Spring, Iceland",
    verdict:"Naturally alkaline volcanic. Very low minerals despite premium positioning. Carbon neutral.",
    pros:["Highest natural pH in database at 8.4","Carbon neutral certified","CarbonFix certified","Volcanic spring origin"],
    cons:["Calcium only 3 mg/L — near zero","Magnesium only 1 mg/L","Premium price for low mineral content","High pH from volcanic geology not minerals"],
    filterNote:"Not applicable — spring water. Consider rotating with high-mineral water.",
    bestFor:"Eco-conscious consumers, high pH preference, gifting",
    avoid:"Those needing mineral supplementation — virtually zero minerals"
  },
  {
    id:14, name:"Topo Chico", tier:"premium", logo:"🫙", pH:5.7,
    calcium:47, magnesium:9, sodium:52, tds:556, bicarbonate:320,
    price:1.50, plastic:false, type:"Natural Sparkling", origin:"Monterrey, Mexico",
    verdict:"Cult-favorite Mexican mineral water. Good Ca moderate TDS. Higher sodium than ideal.",
    pros:["Strong cult following — excellent mixability","Decent calcium at 47 mg/L","Glass bottle","Wide availability via Coca-Cola distribution"],
    cons:["Owned by Coca-Cola since 2017","Sodium 52 mg/L — elevated","Acidic pH from carbonation","Magnesium only 9 mg/L"],
    filterNote:"Not applicable — mineral sparkling water.",
    bestFor:"Cocktail mixer, casual sparkling, Tex-Mex dining",
    avoid:"Those managing sodium intake"
  },
  {
    id:15, name:"Waiakea", tier:"premium", logo:"🌺", pH:8.2,
    calcium:21, magnesium:7, sodium:11, tds:118, bicarbonate:125,
    price:2.40, plastic:true, type:"Volcanic Still", origin:"Mauna Loa, Hawaii",
    verdict:"Naturally alkaline Hawaiian volcanic. Moderate minerals genuine eco-credentials.",
    pros:["Naturally alkaline pH 8.2","Certified B Corporation","CarbonNeutral certified","Hawaiian volcanic aquifer"],
    cons:["Calcium only 21 mg/L — low","Plastic bottle","Premium price for modest minerals","Limited wide distribution"],
    filterNote:"Not applicable — volcanic spring water.",
    bestFor:"Eco-conscious consumers, alkaline preference, mission-driven purchasing",
    avoid:"Those seeking high mineral content"
  },
  {
    id:16, name:"Poland Spring", tier:"midtier", logo:"🌲", pH:7.2,
    calcium:7, magnesium:1, sodium:3, tds:38, bicarbonate:35,
    price:0.90, plastic:true, type:"Natural Still", origin:"Maine, USA",
    verdict:"Genuine US spring at accessible price. Low minerals but balanced pH. Safe daily choice.",
    pros:["Genuine spring water source","Neutral pH 7.2","Very low sodium","Widely available and affordable"],
    cons:["Calcium only 7 mg/L — very low","Magnesium only 1 mg/L — near zero","Owned by BlueTriton — formerly Nestlé","Plastic bottle"],
    filterNote:"Safe to drink. Consider adding mineral drops for nutritional improvement.",
    bestFor:"Everyday hydration on a budget, children's school water",
    avoid:"Those needing mineral supplementation — almost no minerals"
  },
  {
    id:17, name:"Deer Park", tier:"midtier", logo:"🦌", pH:7.0,
    calcium:22, magnesium:5, sodium:7, tds:93, bicarbonate:71,
    price:0.85, plastic:true, type:"Natural Still", origin:"Mid-Atlantic US Springs",
    verdict:"Moderate mineral spring water from Mid-Atlantic. Better minerals than Poland Spring.",
    pros:["Better mineral content than Poland Spring","Multiple spring sources","Affordable price","Neutral pH"],
    cons:["Owned by BlueTriton — formerly Nestlé","Plastic bottle","Magnesium only 5 mg/L","Regional distribution primarily"],
    filterNote:"Safe to drink as is.",
    bestFor:"Mid-Atlantic consumers seeking affordable spring water",
    avoid:"Those needing high magnesium"
  },
  {
    id:18, name:"Arrowhead", tier:"midtier", logo:"🏹", pH:7.7,
    calcium:26, magnesium:9, sodium:5, tds:162, bicarbonate:120,
    price:0.85, plastic:true, type:"Natural Still", origin:"Mountain Springs CA CO",
    verdict:"Western US mountain spring with decent mineral content. Good pH. Reliable West Coast choice.",
    pros:["Good pH at 7.7","Decent mineral content for price","Mountain spring sources","Low sodium"],
    cons:["Owned by BlueTriton — formerly Nestlé","Plastic bottle","Primarily West Coast distribution","Calcium relatively low"],
    filterNote:"Safe to drink as is.",
    bestFor:"West Coast consumers, everyday affordable spring water",
    avoid:"East Coast consumers — limited availability"
  },
  {
    id:19, name:"Zephyrhills", tier:"midtier", logo:"🌴", pH:7.8,
    calcium:55, magnesium:4, sodium:6, tds:196, bicarbonate:188,
    price:0.85, plastic:true, type:"Natural Still", origin:"Florida Springs",
    verdict:"Florida spring with above-average calcium. Great for Southeast consumers.",
    pros:["Above-average calcium at 55 mg/L for price point","Good pH 7.8","Florida spring source","Affordable and widely available in Southeast"],
    cons:["Magnesium only 4 mg/L — very low","Owned by BlueTriton","Plastic bottle","Limited distribution outside Southeast"],
    filterNote:"Safe to drink as is.",
    bestFor:"Florida and Southeast consumers, calcium supplementation on budget",
    avoid:"Those needing magnesium — very low at 4 mg/L"
  },
  {
    id:20, name:"Smartwater", tier:"midtier", logo:"⚡", pH:7.0,
    calcium:15, magnesium:0, sodium:10, tds:55, bicarbonate:0,
    price:1.40, plastic:true, type:"Vapor Distilled", origin:"Municipal tap vapor distilled",
    verdict:"Vapor distilled tap with electrolytes added. Zero Mg is significant gap. Marketing exceeds substance.",
    pros:["Vapor distilled — removes all contaminants","Electrolytes added post-distillation","Sleek marketing and wide availability","Clean neutral taste"],
    cons:["Owned by Coca-Cola","Zero magnesium — significant nutritional gap","Starts as municipal tap water","Premium price for processed tap","Plastic bottle"],
    filterNote:"Source is municipal tap. Distillation is effective but removes beneficial minerals.",
    bestFor:"Contaminant-sensitive consumers who want processed purity",
    avoid:"Those seeking mineral benefit — zero magnesium is a major gap"
  },
  {
    id:21, name:"Essentia", tier:"midtier", logo:"⚗️", pH:9.5,
    calcium:0, magnesium:0, sodium:7, tds:35, bicarbonate:0,
    price:1.80, plastic:true, type:"Ionized Alkaline", origin:"Municipal tap ionized",
    verdict:"High pH via ionization NOT natural minerals. Zero Ca and Mg undermines all alkaline health claims.",
    pros:["Very high pH 9.5","Wide availability","Purified source removes contaminants","Wide distribution"],
    cons:["Owned by Nestlé","Zero calcium and magnesium","pH by ionization not minerals","Premium price for processed tap","Alkaline claims not mineral-supported"],
    filterNote:"Source is municipal tap. Ionization raises pH but adds no mineral benefit.",
    bestFor:"Those wanting high pH water regardless of mineral content",
    avoid:"Those believing alkaline pH equals mineral benefit — it does not here"
  },
  {
    id:22, name:"Eternal", tier:"midtier", logo:"♾️", pH:8.1,
    calcium:22, magnesium:8, sodium:6, tds:100, bicarbonate:95,
    price:1.30, plastic:true, type:"Natural Still", origin:"Natural Springs USA Canada",
    verdict:"Naturally alkaline spring with modest minerals. Better than artificially alkaline brands.",
    pros:["Naturally alkaline pH 8.1 — not ionized","Genuine spring sources","Decent mineral content for price","Low sodium"],
    cons:["Plastic bottle","Modest mineral content","Limited brand recognition","Distribution inconsistent"],
    filterNote:"Not applicable — spring water.",
    bestFor:"Budget alkaline water seekers who want natural not ionized pH",
    avoid:"Those needing significant mineral supplementation"
  },
  {
    id:23, name:"Core Hydration", tier:"midtier", logo:"🔵", pH:7.4,
    calcium:0, magnesium:0, sodium:0, tds:10, bicarbonate:0,
    price:1.50, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Ultra-purified near-zero TDS with pH adjusted. Despite claims mineral content is essentially zero.",
    pros:["Ultra-pure water — all contaminants removed","pH balanced to 7.4","Unique bottle design","Widely available"],
    cons:["Owned by Keurig Dr Pepper","Zero minerals — calcium and magnesium both 0","Starts as municipal tap","Near-zero TDS means aggressive water","Premium price for processed tap"],
    filterNote:"Source is municipal tap. Purification effective but leaves no mineral benefit.",
    bestFor:"Contaminant removal priority, unique bottle aesthetic",
    avoid:"Those seeking mineral benefit — zero minerals"
  },
  {
    id:24, name:"Liquid Death", tier:"specialty", logo:"💀", pH:7.0,
    calcium:14, magnesium:5, sodium:10, tds:100, bicarbonate:74,
    price:1.80, plastic:false, type:"Natural Still", origin:"Austrian Alps, Austria",
    verdict:"Austrian alpine water in aluminum cans. Decent minerals for price. Sustainable packaging positive.",
    pros:["Aluminum can — infinitely recyclable","Austrian alpine source","Decent mineral content for price","Drives younger demographic to hydration"],
    cons:["Marketing gimmick concerns","Calcium relatively low at 14 mg/L","Higher price than mineral content justifies","Can affect taste slightly"],
    filterNote:"Not applicable — alpine spring water.",
    bestFor:"Eco-conscious younger consumers, concert and festival hydration",
    avoid:"Those seeking high mineral content for health"
  },
  {
    id:25, name:"Flow Alkaline", tier:"specialty", logo:"🌊", pH:8.1,
    calcium:38, magnesium:13, sodium:6, tds:148, bicarbonate:128,
    price:2.20, plastic:false, type:"Artesian Alkaline", origin:"Canadian Artesian Spring",
    verdict:"Naturally alkaline Canadian artesian with real minerals behind the pH. Eco-friendly packaging.",
    pros:["Naturally alkaline from artesian source","Plant-based Tetra Pak packaging","Decent mineral content","Certified B Corporation"],
    cons:["Premium price","Limited distribution","Tetra Pak packaging divides opinion","Calcium moderate at 38 mg/L"],
    filterNote:"Not applicable — artesian spring water.",
    bestFor:"Eco-conscious consumers wanting naturally alkaline water with real minerals",
    avoid:"Those needing maximum mineral density"
  },
  {
    id:26, name:"Just Water", tier:"specialty", logo:"🌍", pH:8.0,
    calcium:24, magnesium:8, sodium:5, tds:98, bicarbonate:90,
    price:1.90, plastic:false, type:"Natural Still", origin:"Glens Falls, NY Spring",
    verdict:"Naturally alkaline NY spring in plant-based packaging. Decent minerals strong eco credentials.",
    pros:["Plant-based paper bottle","Naturally alkaline pH 8.0","New York spring source","Co-founded by Jaden Smith — mission brand"],
    cons:["Modest mineral content","Premium price","Limited distribution","Paper bottle durability concerns"],
    filterNote:"Not applicable — spring water.",
    bestFor:"Eco-conscious consumers, mission-driven purchasing, alkaline preference",
    avoid:"Those seeking high mineral content"
  },
  {
    id:27, name:"LaCroix", tier:"specialty", logo:"🌈", pH:4.7,
    calcium:0, magnesium:0, sodium:2, tds:10, bicarbonate:0,
    price:0.85, plastic:false, type:"Sparkling Purified", origin:"Municipal tap plus CO2",
    verdict:"Popular purified sparkling. Acidic pH from carbonation. Zero minerals. Occasional variety only.",
    pros:["Very low sodium at 2 mg/L","Wide variety of natural flavors","Aluminum can — recyclable","Affordable price"],
    cons:["Owned by National Beverage Corp","Zero minerals","Very acidic pH 4.7 — tooth enamel concern","Starts as municipal tap water","Should not be primary water"],
    filterNote:"Source is municipal tap. Carbonation creates acidic pH. Use as occasional variety only.",
    bestFor:"Flavor variety, occasional sparkling, soda replacement",
    avoid:"Do not use as primary water — acidic and zero minerals"
  },
  {
    id:28, name:"Pure Life", tier:"budget", logo:"💧", pH:7.2,
    calcium:18, magnesium:5, sodium:8, tds:95, bicarbonate:45,
    price:0.60, plastic:true, type:"Purified Remineralized", origin:"Municipal tap remineralized",
    verdict:"Purified tap with minerals added back. Balanced LSI. Best budget remineralized option.",
    pros:["Minerals added back after purification","Balanced pH 7.2","Best mineral content in budget category","Affordable and widely available"],
    cons:["Owned by BlueTriton — formerly Nestlé","Starts as municipal tap","Plastic bottle","Mineral levels still modest"],
    filterNote:"Source is municipal tap with remineralization. Among better budget options.",
    bestFor:"Budget-conscious families wanting some mineral benefit",
    avoid:"Those seeking spring water authenticity"
  },
  {
    id:29, name:"Dasani", tier:"budget", logo:"🏭", pH:5.6,
    calcium:0, magnesium:0, sodium:6, tds:20, bicarbonate:0,
    price:0.80, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Filtered municipal with acidic pH and near-zero minerals. One of the poorest health choices available.",
    pros:["Removes contaminants via reverse osmosis","Widely available everywhere","Consistent taste","Affordable"],
    cons:["Owned by Coca-Cola","Acidic pH 5.6 — aggressive to teeth and body","Zero calcium and magnesium","Starts as municipal tap","Premium price with no mineral benefit"],
    filterNote:"Source is municipal tap. RO removes contaminants but also all minerals. Add mineral drops.",
    bestFor:"Emergency hydration when nothing else available",
    avoid:"Daily use — acidic pH and zero minerals are concerning long-term"
  },
  {
    id:30, name:"Aquafina", tier:"budget", logo:"🏭", pH:6.0,
    calcium:0, magnesium:0, sodium:0, tds:10, bicarbonate:0,
    price:0.75, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Lowest TDS in database. Near-maximally aggressive. Removes contaminants AND all beneficial minerals.",
    pros:["Removes all contaminants including heavy metals","Purest contaminant removal","Widely available","Low price"],
    cons:["Owned by PepsiCo","Near-zero TDS — most aggressive water in database","Zero calcium magnesium and sodium","Starts as municipal tap","Acidic pH 6.0"],
    filterNote:"Source is municipal tap. Most aggressive water profile in database. Add mineral drops urgently.",
    bestFor:"Situations requiring maximum contaminant removal only",
    avoid:"Daily use — most aggressive mineral-stripping water in entire database"
  },
  {
    id:31, name:"Great Value", tier:"budget", logo:"🛒", pH:6.5,
    calcium:0, magnesium:0, sodium:5, tds:15, bicarbonate:0,
    price:0.25, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Walmart store brand. Lowest cost accessible. Better pH than Dasani. Zero minerals but clean water.",
    pros:["Lowest accessible price point","Better pH than Dasani and Aquafina","Widely available at Walmart","Removes contaminants"],
    cons:["Walmart house brand","Zero minerals","Starts as municipal tap","Plastic bottle","Slightly acidic pH 6.5"],
    filterNote:"Source is municipal tap. Safe but zero mineral value. Best used with mineral drops.",
    bestFor:"Budget access to clean water, food deserts, large families on tight budget",
    avoid:"Those seeking mineral benefit"
  },
  {
    id:32, name:"Kirkland Still", tier:"budget", logo:"🏪", pH:6.8,
    calcium:0, magnesium:0, sodium:3, tds:15, bicarbonate:0,
    price:0.20, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Costco bulk. Best value per gallon. Better pH than most purified waters. Zero minerals.",
    pros:["Best price per gallon in database","Better pH than Dasani and Aquafina","Costco quality control","Very low sodium"],
    cons:["Costco house brand","Zero minerals","Starts as municipal tap","Bulk only — requires Costco membership","Plastic"],
    filterNote:"Source is municipal tap. Excellent value. Add mineral drops for health improvement.",
    bestFor:"Costco members, bulk buying, large families",
    avoid:"Those needing minerals — zero mineral content"
  },
  {
    id:33, name:"Crystal Geyser", tier:"budget", logo:"🗻", pH:6.9,
    calcium:14, magnesium:5, sodium:4, tds:74, bicarbonate:57,
    price:0.50, plastic:true, type:"Natural Still", origin:"Mount Shasta, CA Springs",
    verdict:"Genuine spring from Mt. Shasta at budget price. Best mineral-containing option at the budget tier.",
    pros:["Genuine spring water — not municipal tap","Some mineral content at budget price","Low sodium","Independent company — CG Roxane"],
    cons:["Calcium only 14 mg/L — modest","Slightly acidic pH 6.9","Plastic bottle","Primarily West Coast distribution"],
    filterNote:"Not applicable — genuine spring water. Best budget mineral option.",
    bestFor:"Budget-conscious West Coast consumers wanting real spring water",
    avoid:"East Coast consumers — distribution limited"
  },
  {
    id:34, name:"Dollar Tree Spring", tier:"budget", logo:"🌳", pH:6.7,
    calcium:0, magnesium:0, sodium:5, tds:15, bicarbonate:0,
    price:0.17, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Lowest cost in database. Critically important clean water access for underserved communities.",
    pros:["Lowest price in entire database","Safe purified water","Critical access point for food deserts","Nationwide Dollar Tree availability"],
    cons:["Zero minerals","Slightly acidic pH 6.7","Starts as municipal tap","Plastic bottle","No nutritional value beyond hydration"],
    filterNote:"Source is municipal tap. Safe but zero minerals. Most important access-point water in database.",
    bestFor:"Underserved communities, emergency access, absolute minimum budget",
    avoid:"Those with choice — upgrade to mineral water when possible"
  },
  {
    id:35, name:"Kirkland Sparkling", tier:"budget", logo:"🫧", pH:5.8,
    calcium:35, magnesium:8, sodium:8, tds:130, bicarbonate:105,
    price:0.35, plastic:false, type:"Natural Sparkling", origin:"Natural Spring plus CO2",
    verdict:"Costco sparkling with real spring minerals. Best value sparkling water with actual mineral content.",
    pros:["Real spring minerals — calcium 35 mg/L","Aluminum can — recyclable","Best value sparkling with real mineral content","Low sodium"],
    cons:["Acidic pH from carbonation","Costco membership required","Calcium content modest","Carbonation may cause bloating"],
    filterNote:"Not applicable — spring-based sparkling water.",
    bestFor:"Costco members wanting affordable sparkling with real minerals",
    avoid:"Those sensitive to carbonation or acidic pH"
  },
  {
    id:36, name:"Aldi Aqua D'or", tier:"budget", logo:"🏷️", pH:7.0,
    calcium:0, magnesium:0, sodium:5, tds:15, bicarbonate:0,
    price:0.19, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Aldi house brand. Neutral pH is one of best in budget purified category. Excellent community value.",
    pros:["Neutral pH 7.0 — best pH in budget purified category","Very low price","Widely available at Aldi","Removes contaminants"],
    cons:["Zero minerals","Starts as municipal tap water","Plastic bottle","Aldi store access required","No mineral nutritional value"],
    filterNote:"Source is municipal tap. Best pH of any budget purified brand. Add mineral drops.",
    bestFor:"Aldi shoppers, budget access to neutral pH water",
    avoid:"Those needing mineral benefit"
  },
  {
    id:37, name:"Members Mark", tier:"budget", logo:"🏬", pH:6.7,
    calcium:0, magnesium:0, sodium:4, tds:14, bicarbonate:0,
    price:0.22, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Sams Club store brand. Ultra-low cost clean water. Widely available very affordable for families.",
    pros:["Ultra-low price","Bulk availability at Sams Club","Removes contaminants","Low sodium"],
    cons:["Walmart/Sams Club house brand","Zero minerals","Slightly acidic pH 6.7","Starts as municipal tap","Plastic bottle"],
    filterNote:"Source is municipal tap. Safe but zero mineral benefit.",
    bestFor:"Sams Club members, bulk family hydration",
    avoid:"Those seeking mineral benefit"
  },
  {
    id:38, name:"Niagara", tier:"budget", logo:"🌊", pH:6.9,
    calcium:0, magnesium:0, sodium:5, tds:18, bicarbonate:0,
    price:0.28, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"One of largest US bottlers. Reasonable pH for a purified product. Budget accessible.",
    pros:["One of largest US independent bottlers","Reasonable pH for purified product","Affordable price","Wide distribution"],
    cons:["Zero minerals","Starts as municipal tap water","Slightly acidic pH 6.9","Plastic bottle","No mineral benefit"],
    filterNote:"Source is municipal tap. Safe. No mineral benefit.",
    bestFor:"Everyday budget hydration, large volume needs",
    avoid:"Those seeking mineral content"
  },
  {
    id:39, name:"Target GoodGather", tier:"budget", logo:"🎯", pH:7.0,
    calcium:0, magnesium:0, sodium:4, tds:12, bicarbonate:0,
    price:0.22, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Target house brand. Clean neutral pH. Zero minerals. One of cleaner-profile budget purified waters.",
    pros:["Neutral pH 7.0","Low price","Target availability nationwide","Removes contaminants"],
    cons:["Target house brand","Zero minerals","Starts as municipal tap water","Plastic bottle","No mineral nutritional value"],
    filterNote:"Source is municipal tap. Neutral pH is positive. No mineral benefit.",
    bestFor:"Target shoppers wanting clean affordable water",
    avoid:"Those needing mineral benefit"
  },
  {
    id:40, name:"Proud Source", tier:"specialty", logo:"🏔️", pH:7.8,
    calcium:35, magnesium:12, sodium:7, tds:148, bicarbonate:140,
    price:2.10, plastic:false, type:"Artesian Still", origin:"Snake River Plain Aquifer, ID",
    verdict:"Idaho artesian in aluminum can. Good mineral profile naturally alkaline. Strong health and eco profile.",
    pros:["Aluminum can — infinitely recyclable","Naturally alkaline pH 7.8","Idaho artesian aquifer source","Decent mineral content"],
    cons:["Premium price","Limited distribution","Calcium moderate at 35 mg/L","Independent brand — availability inconsistent"],
    filterNote:"Not applicable — artesian spring water.",
    bestFor:"Eco-conscious consumers wanting artesian water in sustainable packaging",
    avoid:"Those needing maximum mineral density"
  },
  {
    id:41, name:"DG Drinking Water", tier:"budget", logo:"🟡", pH:6.8,
    calcium:0, magnesium:0, sodium:5, tds:14, bicarbonate:0,
    price:0.16, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Dollar General house brand. Widest rural and low-income community access. Zero minerals but safe.",
    pros:["Extremely low price — among cheapest in database","Critical rural access — Dollar General in 47 states","Removes contaminants","Safe hydration baseline"],
    cons:["Dollar General house brand","Zero minerals","Starts as municipal tap","Slightly acidic pH 6.8","Plastic bottle"],
    filterNote:"Source is municipal tap. Safe. No mineral benefit.",
    bestFor:"Rural communities, underserved areas, absolute minimum budget access",
    avoid:"Those with access to better options — zero mineral content"
  },
  {
    id:42, name:"365 Whole Foods", tier:"midtier", logo:"🌱", pH:7.2,
    calcium:12, magnesium:4, sodium:6, tds:58, bicarbonate:42,
    price:1.10, plastic:true, type:"Purified Spring Blend", origin:"Municipal and spring blend",
    verdict:"Whole Foods house brand. Modest minerals. Mid-tier pricing. Best for Whole Foods shoppers wanting affordable in-store option.",
    pros:["Whole Foods quality control","Modest mineral content","Reasonable price for Whole Foods","Amazon Prime delivery available"],
    cons:["Owned by Amazon — corporate concerns","Modest mineral content for price","Plastic bottle","Spring blend not pure spring"],
    filterNote:"Blend of purified and spring sources. Modest mineral benefit.",
    bestFor:"Whole Foods shoppers, Amazon Prime members wanting affordable in-store water",
    avoid:"Those seeking premium mineral content"
  },
  {
    id:43, name:"Trader Joes", tier:"budget", logo:"🔴", pH:7.1,
    calcium:8, magnesium:2, sodium:4, tds:42, bicarbonate:32,
    price:0.35, plastic:true, type:"Natural Still", origin:"Mountain Springs blend",
    verdict:"Trader Joes house brand spring water. Good value. Light minerals. Consistent quality for the price.",
    pros:["Genuine spring source blend","Good value per liter","Neutral pH 7.1","Low sodium"],
    cons:["Owned by Aldi Group","Low mineral content","Plastic bottle","Trader Joes access required","Distribution limited to TJ stores"],
    filterNote:"Genuine spring blend. Low but real mineral content.",
    bestFor:"Trader Joes shoppers seeking affordable spring water",
    avoid:"Those needing significant mineral supplementation"
  },
  {
    id:44, name:"Publix Water", tier:"budget", logo:"🟢", pH:7.0,
    calcium:0, magnesium:0, sodium:4, tds:12, bicarbonate:0,
    price:0.24, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Publix store brand purified water. Neutral pH a positive. Southeast staple. Zero minerals.",
    pros:["Neutral pH 7.0","Low price","Publix quality standards","Southeast wide availability"],
    cons:["Publix house brand","Zero minerals","Starts as municipal tap","Plastic bottle","Publix store access required"],
    filterNote:"Source is municipal tap. Neutral pH is positive. No mineral benefit.",
    bestFor:"Southeast Publix shoppers wanting budget clean water",
    avoid:"Those needing mineral benefit"
  },
  {
    id:45, name:"Kroger Water", tier:"budget", logo:"🛒", pH:6.9,
    calcium:0, magnesium:0, sodium:5, tds:15, bicarbonate:0,
    price:0.22, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Kroger house brand. Nationwide grocery access. Reasonable pH. Zero minerals.",
    pros:["Kroger nationwide access — 2800 stores","Reasonable price","Removes contaminants","Low sodium"],
    cons:["Kroger house brand","Zero minerals","Starts as municipal tap","Slightly acidic pH 6.9","Plastic bottle"],
    filterNote:"Source is municipal tap. Safe. No mineral benefit.",
    bestFor:"Kroger shoppers, budget everyday hydration",
    avoid:"Those seeking mineral benefit"
  },
  {
    id:46, name:"CVS Water", tier:"budget", logo:"🔴", pH:7.0,
    calcium:0, magnesium:0, sodium:4, tds:12, bicarbonate:0,
    price:0.30, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"CVS pharmacy brand. Convenient single-serve access. Neutral pH. Zero minerals.",
    pros:["CVS pharmacy access — 9000 plus locations","Neutral pH 7.0","Convenient for pharmacy visits","Removes contaminants"],
    cons:["CVS house brand","Zero minerals","Starts as municipal tap","Higher per-unit cost than bulk","Plastic bottle"],
    filterNote:"Source is municipal tap. Safe convenience option. No mineral benefit.",
    bestFor:"Emergency hydration, pharmacy convenience, single-serve on the go",
    avoid:"Daily use — expensive per liter and zero minerals"
  },
  {
    id:47, name:"Walgreens Water", tier:"budget", logo:"🔵", pH:7.0,
    calcium:0, magnesium:0, sodium:4, tds:12, bicarbonate:0,
    price:0.30, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Walgreens pharmacy brand. Neutral pH positive. Convenient access. Zero minerals.",
    pros:["Walgreens access — 8700 plus locations","Neutral pH 7.0","Convenient for pharmacy access","Safe purified water"],
    cons:["Walgreens house brand","Zero minerals","Starts as municipal tap","Higher per-unit cost","Plastic bottle"],
    filterNote:"Source is municipal tap. Neutral pH is positive. No mineral benefit.",
    bestFor:"Emergency hydration, pharmacy convenience purchase",
    avoid:"Daily use — premium price for zero mineral benefit"
  },
  {
    id:48, name:"Wegmans Water", tier:"budget", logo:"🟠", pH:7.1,
    calcium:6, magnesium:2, sodium:3, tds:28, bicarbonate:22,
    price:0.28, plastic:true, type:"Natural Still", origin:"Northeast Spring Sources",
    verdict:"Wegmans house brand spring water. Northeast regional gem. Light minerals. Good value.",
    pros:["Genuine spring source","Light mineral content","Good value","Wegmans quality reputation — highly rated grocer"],
    cons:["Wegmans house brand","Low mineral content","Limited to Wegmans footprint — Northeast only","Plastic bottle"],
    filterNote:"Genuine spring source. Light but real minerals.",
    bestFor:"Northeast Wegmans shoppers wanting affordable spring water",
    avoid:"Those outside Wegmans service area"
  },
  {
    id:49, name:"HEB Water", tier:"budget", logo:"🤠", pH:7.0,
    calcium:0, magnesium:0, sodium:4, tds:13, bicarbonate:0,
    price:0.20, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"HEB store brand. Texas and South Texas institution. Neutral pH. Zero minerals. Excellent value.",
    pros:["HEB beloved Texas institution — excellent store quality","Neutral pH 7.0","Very low price","Removes contaminants"],
    cons:["HEB house brand","Zero minerals","Starts as municipal tap","Plastic bottle","Texas and South Texas distribution only"],
    filterNote:"Source is municipal tap. Neutral pH is positive. No mineral benefit.",
    bestFor:"Texas HEB shoppers, South Texas communities",
    avoid:"Those outside HEB service area or needing mineral benefit"
  },
  {
    id:50, name:"Wawa Water", tier:"budget", logo:"🦢", pH:7.1,
    calcium:0, magnesium:0, sodium:4, tds:14, bicarbonate:0,
    price:0.32, plastic:true, type:"Purified", origin:"Municipal tap purified",
    verdict:"Wawa convenience brand. Mid-Atlantic and Southeast institution. Neutral pH. Clean and convenient.",
    pros:["Wawa beloved Mid-Atlantic brand","Neutral pH 7.1","Convenient — Wawa open 24/7","Safe purified water"],
    cons:["Wawa house brand","Zero minerals","Starts as municipal tap","Higher convenience premium","Plastic bottle"],
    filterNote:"Source is municipal tap. Safe convenience option.",
    bestFor:"Mid-Atlantic Wawa customers, late night convenience, road trips",
    avoid:"Daily primary water — convenience premium with zero minerals"
  },
  {
    id:51, name:"Sparkling Ice", tier:"specialty", logo:"✨", pH:3.8,
    calcium:0, magnesium:0, sodium:0, tds:8, bicarbonate:0,
    price:0.90, plastic:true, type:"Flavored Sparkling Purified", origin:"Municipal tap purified with flavoring",
    verdict:"Heavily marketed flavored sparkling. Most acidic water in database at pH 3.8. Soda replacement not health upgrade.",
    pros:["Wide variety of flavors","Zero sugar","Caffeine versions available","Widely available"],
    cons:["MOST acidic water in entire database — pH 3.8 is extremely damaging to tooth enamel","Zero minerals","Starts as municipal tap","Owned by Talking Rain","Citric acid added — increases acidity","Should NOT be called water health-wise"],
    filterNote:"Source is municipal tap. Extremely acidic. Not a healthy water choice.",
    bestFor:"Soda replacement for flavor variety only — occasional use",
    avoid:"Daily use — pH 3.8 is severely damaging to tooth enamel. Not a genuine water product."
  },
  {
    id:52, name:"Bodyarmor Water", tier:"midtier", logo:"🏋️", pH:7.4,
    calcium:0, magnesium:0, sodium:0, tds:10, bicarbonate:0,
    price:1.60, plastic:true, type:"Purified Alkaline", origin:"Municipal tap purified",
    verdict:"Coca-Cola sports hydration brand. Purified alkaline. Zero minerals. Premium price for processed tap.",
    pros:["Owned by Coca-Cola — wide distribution","Neutral to slightly alkaline pH","Popular sports brand","Wide retail availability"],
    cons:["Owned by Coca-Cola","Zero calcium and magnesium","Starts as municipal tap","Premium price for processed tap","Alkaline not from minerals"],
    filterNote:"Source is municipal tap. Sports marketing does not add mineral benefit.",
    bestFor:"Brand-conscious sports consumers, gym hydration when convenience matters",
    avoid:"Those seeking genuine mineral benefit from their water"
  },
  {
    id:53, name:"Prime Hydration", tier:"specialty", logo:"⚡", pH:7.4,
    calcium:0, magnesium:0, sodium:65, tds:35, bicarbonate:0,
    price:1.80, plastic:true, type:"Enhanced Water", origin:"Municipal tap purified with electrolytes",
    verdict:"Logan Paul and KSI influencer brand. High sodium electrolyte drink. Not a mineral water. Sports and youth marketing.",
    pros:["Strong youth brand recognition","Electrolytes added","Wide availability at major retailers","Coconut water base in original"],
    cons:["Influencer marketing product not genuine water","High sodium 65 mg/L","Zero calcium and magnesium","Starts as municipal tap","Premium influencer price premium","Not a mineral water product"],
    filterNote:"Enhanced municipal tap water. Electrolytes added but no mineral benefit.",
    bestFor:"Youth market, post-workout electrolyte replacement, brand fans",
    avoid:"Those seeking genuine mineral water benefit — this is a sports drink not water"
  },
  {
    id:54, name:"Liquid IV", tier:"specialty", logo:"💊", pH:7.2,
    calcium:0, magnesium:0, sodium:500, tds:280, bicarbonate:0,
    price:2.20, plastic:true, type:"Electrolyte Enhanced", origin:"Powder mixed with purified water",
    verdict:"Electrolyte multiplier product. Extremely high sodium. Medical hydration use case not daily water.",
    pros:["Owned by Unilever — quality standards","Effective for severe dehydration recovery","Clinically formulated electrolyte ratios","Wide availability"],
    cons:["Owned by Unilever","Sodium 500 mg/L — extremely high","Zero calcium and magnesium","Designed for medical rehydration not daily use","Very expensive per liter"],
    filterNote:"Electrolyte product not standard water. Not for daily use.",
    bestFor:"Severe dehydration recovery, athletic endurance events, illness recovery",
    avoid:"Daily use — extremely high sodium content not appropriate for regular hydration"
  },
  {
    id:55, name:"Propel", tier:"midtier", logo:"🏃", pH:3.8,
    calcium:0, magnesium:0, sodium:160, tds:95, bicarbonate:0,
    price:1.20, plastic:true, type:"Flavored Electrolyte Water", origin:"Municipal tap purified with electrolytes",
    verdict:"PepsiCo fitness water. Extremely acidic pH 3.8. Very high sodium. Sports drink disguised as water.",
    pros:["PepsiCo wide distribution","Electrolytes added","Popular fitness brand","Available in many flavors"],
    cons:["Owned by PepsiCo","Extremely acidic pH 3.8 — tied with Sparkling Ice for worst pH","Very high sodium 160 mg/L","Zero calcium and magnesium","Starts as municipal tap","Sports drink not genuine water"],
    filterNote:"Acidic sports drink product. Not appropriate as daily water.",
    bestFor:"Intense athletic activity electrolyte replacement only",
    avoid:"Daily use — pH 3.8 damages tooth enamel and high sodium concerning for regular consumption"
  },
];

export const FILTER_RECOMMENDATIONS = {
  PFAS: {
    problem: "PFAS Forever Chemicals",
    icon: "☢️",
    urgency: "HIGH",
    description: "PFAS are man-made chemicals that do not break down in the environment or your body. Linked to cancer, thyroid disease, immune suppression, and developmental issues in children. EPA health advisory is 4 ppt. Many US cities exceed this by hundreds of times.",
    solutions: [
      { type: "Reverse Osmosis", effectiveness: "95% plus removal", brands: ["APEC ROES-50 — $200", "iSpring RCC7 — $190", "Home Master TMAFC — $350"], cost: "$150-400", note: "Best overall PFAS removal — Walter top recommendation" },
      { type: "Activated Carbon Block", effectiveness: "70-80% removal", brands: ["Berkey — $250", "Clearly Filtered — $90", "Aquasana — $100"], cost: "$50-200", note: "Good but not as complete as RO" },
      { type: "Does NOT work", effectiveness: "0% removal", brands: ["Brita pitcher", "PUR standard", "Refrigerator filters"], cost: "N/A", note: "Standard carbon filters do NOT remove PFAS — do not rely on these" },
    ]
  },
  Lead: {
    problem: "Lead Contamination",
    icon: "🔴",
    urgency: "CRITICAL",
    description: "Lead has no safe level of exposure. Causes irreversible neurological damage especially in children under 6. Sources are usually lead service lines or older plumbing installed before 1986. Boiling water does NOT remove lead — it concentrates it.",
    solutions: [
      { type: "Reverse Osmosis", effectiveness: "99% removal", brands: ["APEC ROES-50 — $200", "iSpring RCC7 — $190", "Express Water RO5DX — $150"], cost: "$150-400", note: "Most effective lead removal — Walter top recommendation" },
      { type: "NSF 53 Certified Filter", effectiveness: "95% plus removal", brands: ["Clearly Filtered Pitcher — $90", "Aquasana AQ-5200 — $100", "Berkey with PF-2 — $280"], cost: "$50-300", note: "Must be NSF 53 certified specifically for lead" },
      { type: "Does NOT work", effectiveness: "0% removal", brands: ["Standard Brita", "ZeroWater partial only", "Boiling water"], cost: "N/A", note: "CRITICAL: Boiling water CONCENTRATES lead. Do not boil." },
    ]
  },
  Nitrate: {
    problem: "Nitrate Contamination",
    icon: "🌾",
    urgency: "HIGH",
    description: "Nitrates primarily from agricultural fertilizer runoff. EPA maximum is 10 ppm. Dangerous for infants under 6 months causing blue baby syndrome where blood cannot carry oxygen effectively. Adults with compromised immunity also at risk.",
    solutions: [
      { type: "Reverse Osmosis", effectiveness: "92-95% removal", brands: ["APEC ROES-50 — $200", "Home Master TMAFC — $350", "iSpring RCC7 — $190"], cost: "$150-400", note: "Most effective nitrate removal" },
      { type: "Ion Exchange", effectiveness: "90% plus removal", brands: ["Culligan — call for quote", "Kinetico — call for quote", "EcoWater — call for quote"], cost: "$500-2000 installed", note: "Whole house option for high nitrate areas" },
      { type: "Does NOT work", effectiveness: "0% removal", brands: ["All carbon filters", "UV filters", "Boiling water"], cost: "N/A", note: "Boiling CONCENTRATES nitrates. Carbon filters do not remove nitrates." },
    ]
  },
  General: {
    problem: "General Water Quality Improvement",
    icon: "💧",
    urgency: "MODERATE",
    description: "For cities within regulatory limits but with elevated contaminant levels or multiple violations, a quality carbon block filter provides meaningful improvement to taste, odor, chlorine, and some contaminants.",
    solutions: [
      { type: "Carbon Block Under-Sink", effectiveness: "Good for chlorine, taste, some VOCs", brands: ["Aquasana AQ-5200 — $100", "Culligan US-EZ-4 — $50", "Watts WH-LD — $60"], cost: "$50-200", note: "Best everyday improvement for regulated water" },
      { type: "Reverse Osmosis", effectiveness: "Broadest contaminant removal", brands: ["APEC ROES-50 — $200", "iSpring RCC7 — $190"], cost: "$150-400", note: "Best overall solution for any water quality concern" },
      { type: "Pitcher Filter NSF 53", effectiveness: "Good for lead, chlorine, taste", brands: ["Clearly Filtered — $90", "Aquasana Powered — $100"], cost: "$50-100", note: "Budget-friendly entry point — must be NSF 53 certified" },
    ]
  }
};

export const HOW_TO_READ_DATA = {
  pfas: {
    label: "PFAS Level",
    unit: "ppt (parts per trillion)",
    icon: "☢️",
    levels: [
      { range: "0-4 ppt", status: "Safe", color: "#16a34a", desc: "At or below EPA health advisory. Current best available standard." },
      { range: "4-70 ppt", status: "Elevated", color: "#ca8a04", desc: "Above EPA health advisory. Long-term exposure concern. Filter recommended." },
      { range: "70-200 ppt", status: "High", color: "#ea580c", desc: "Significantly elevated. Walter strongly recommends reverse osmosis filtration immediately." },
      { range: "200+ ppt", status: "CRISIS", color: "#dc2626", desc: "Crisis level. Avoid tap water for drinking and cooking. Use filtered or bottled water only." },
    ],
    walterNote: "PFAS are forever chemicals — they accumulate in your body over time. Even low levels have cumulative effects. The only way to remove them is reverse osmosis or activated carbon block filtration."
  },
  lead: {
    label: "Lead Level",
    unit: "ppb (parts per billion)",
    icon: "🔴",
    levels: [
      { range: "0-3.8 ppb", status: "Safe", color: "#16a34a", desc: "Below WHO guideline. Generally safe for most adults." },
      { range: "3.8-15 ppb", status: "Elevated", color: "#ca8a04", desc: "Elevated. Children and pregnant women should use filtered water." },
      { range: "15+ ppb", status: "Action Level", color: "#dc2626", desc: "EPA action level exceeded. Immediate filtration required. No safe level for children." },
    ],
    walterNote: "There is NO safe level of lead for children under 6. If your home was built before 1986 you may have lead service lines regardless of your city score. Test your home water separately."
  },
  nitrate: {
    label: "Nitrate Level",
    unit: "ppm (parts per million)",
    icon: "🌾",
    levels: [
      { range: "0-3 ppm", status: "Safe", color: "#16a34a", desc: "Well below EPA maximum. No concern for most people." },
      { range: "3-10 ppm", status: "Moderate", color: "#ca8a04", desc: "Approaching EPA maximum. Infants and pregnant women should use filtered water." },
      { range: "10+ ppm", status: "Exceeds Limit", color: "#dc2626", desc: "Exceeds EPA maximum contaminant level. Do not give to infants under 6 months. Filter required." },
    ],
    walterNote: "Nitrates are primarily an infant risk. Healthy adults can tolerate moderate nitrate levels but infants under 6 months can develop blue baby syndrome which can be fatal."
  },
  violations: {
    label: "5-Year Violations",
    unit: "count",
    icon: "⚠️",
    levels: [
      { range: "0", status: "Excellent", color: "#16a34a", desc: "Zero violations in 5 years. Exceptional compliance record." },
      { range: "1-3", status: "Good", color: "#16a34a", desc: "Minor violations. Generally well-managed utility." },
      { range: "4-7", status: "Moderate Concern", color: "#ca8a04", desc: "Multiple violations indicate recurring compliance challenges." },
      { range: "8+", status: "High Concern", color: "#dc2626", desc: "Persistent violations indicate systemic compliance failure. Request your CCR report immediately." },
    ],
    walterNote: "A violation does not always mean your water was unsafe — it can include monitoring failures and reporting issues. But repeated violations indicate management problems worth investigating."
  },
  lsi: {
    label: "LSI Score",
    unit: "index",
    icon: "🔬",
    levels: [
      { range: "Below -0.5", status: "Aggressive", color: "#dc2626", desc: "Water actively dissolves minerals it contacts including calcium in teeth and bones." },
      { range: "-0.5 to -0.2", status: "Mildly Aggressive", color: "#ea580c", desc: "Mild mineral depletion risk. Limited mineral contribution to your body." },
      { range: "-0.2 to +0.2", status: "Balanced", color: "#16a34a", desc: "Ideal range. Water is in equilibrium with your body. Neither deposits nor removes minerals." },
      { range: "Above +0.2", status: "Scaling", color: "#ca8a04", desc: "High mineral content. Beneficial but may cause scale buildup in pipes." },
    ],
    walterNote: "LSI is the single most important number for understanding whether your water is working for or against your body. Most purified bottled waters score -1.0 to -2.0 — aggressively stripping your minerals."
  }
};

export const CIVIC_CONTACTS = {
  federal: [
    { name: "EPA Safe Drinking Water Hotline", phone: "1-800-426-4791", website: "epa.gov/ground-water-and-drinking-water", note: "Report violations, request information, file formal complaints about your utility" },
    { name: "EPA Regional Offices", phone: "1-202-564-4700", website: "epa.gov/aboutepa/regional-and-geographic-offices", note: "Find your regional EPA office for local contamination issues" },
    { name: "CDC Environmental Health", phone: "1-800-232-4636", website: "cdc.gov/nceh", note: "Health impacts of environmental contamination and exposure assessment" },
    { name: "Agency for Toxic Substances", phone: "1-800-232-4636", website: "atsdr.cdc.gov", note: "PFAS and heavy metal health exposure information and community assistance" },
  ],
  advocacy: [
    { name: "Environmental Working Group Tap Water Database", website: "ewg.org/tapwater", note: "Search your zip code for detailed contaminant levels — the most comprehensive public database" },
    { name: "Clean Water Action", website: "cleanwater.org", note: "National advocacy — find your local chapter and connect with community organizers" },
    { name: "Natural Resources Defense Council", website: "nrdc.org/issues/clean-water", note: "Legal advocacy, water quality reports, and policy analysis" },
    { name: "American Rivers", website: "americanrivers.org", note: "River protection and source water advocacy" },
    { name: "Waterkeeper Alliance", website: "waterkeeper.org", note: "Local waterkeeper organizations in your watershed — boots on ground advocacy" },
  ],
  howTo: [
    { action: "Request Your CCR Right Now", description: "Every water utility must provide a Consumer Confidence Report free by law. Call your utility and say: I am requesting my Consumer Confidence Report under the Safe Drinking Water Act. They must comply. This lists every contaminant detected last year and the legal limit." },
    { action: "File an EPA Formal Complaint", description: "If your utility is violating the Safe Drinking Water Act you have the right to file a formal complaint at epa.gov. Document every violation notice you receive. Keep copies of everything. Complaints create official records utilities must respond to." },
    { action: "Contact Your City Council Member", description: "Water infrastructure is a local government responsibility. City council members control utility budgets and appointment of utility boards. Attend public meetings and speak during public comment period. Elected officials respond to constituent pressure — especially organized groups." },
    { action: "Contact Your State Environmental Agency", description: "Every state has an environmental protection agency that oversees drinking water utilities. Find yours at epa.gov/home/health-and-environmental-agencies-us-states-and-territories. State agencies have direct enforcement authority your city utility must answer to." },
    { action: "Contact Your US Congressional Representatives", description: "Federal funding for water infrastructure comes through Congress. Contact your US Senator and House Representative through congress.gov. Reference the Safe Drinking Water Act, Lead and Copper Rule, and Bipartisan Infrastructure Law water provisions. Congressional attention accelerates local action." },
    { action: "Organize Your Neighbors", description: "Individual complaints get filed. Organized community pressure gets action. Use Nextdoor, local Facebook groups, and neighborhood associations to share Flo·zēk data with your community. A group of 50 residents showing up to a city council meeting with contamination data gets results that a single complaint never will." },
    { action: "Contact Local Media", description: "Local TV news and newspapers respond strongly to water quality stories with data. Share your city's Flo·zēk report card with your local news station. Journalists covering environmental issues will investigate and public pressure from news coverage is one of the fastest ways to force utility action." },
  ]
};

export const WALTER_QA_PROMPTS = [
  "Is my city's water safe for my baby or young children?",
  "What filter should I buy to remove PFAS from my tap water?",
  "My city has high lead levels — what should I do right now?",
  "Which bottled water has the best mineral content for daily use?",
  "What does my LSI score mean for my health?",
  "How do I compare my tap water to bottled water?",
  "My house was built before 1986 — should I be worried about lead pipes?",
  "What is the difference between reverse osmosis and a carbon filter?",
  "Which brands does Walter recommend avoiding and why?",
  "How do I get my utility to give me my water quality report?",
  "What contaminants does Brita actually remove?",
  "Is sparkling water acidic enough to damage my teeth?",
  "Why does Dasani taste different from spring water?",
  "What minerals should I look for on a water label?",
  "How can I take action about my city's water quality?",
];

export const CITIES = [
  { name:"New York City", state:"NY", pH:7.2, tds:50, calcium:14, bicarbonate:30, region:"tristate", pfas:11, lead:5.2, nitrate:0.5, violations:6, source:"Catskill / Delaware / Croton Watersheds", contaminants:"Lead service lines, HABs, DBPs" },
  { name:"Los Angeles", state:"CA", pH:7.8, tds:280, calcium:68, bicarbonate:120, region:"west", pfas:28, lead:3.4, nitrate:1.0, violations:7, source:"MWD Colorado River / LA Aqueduct", contaminants:"PFAS, Chromium-6, Perchlorate, Lead" },
  { name:"Chicago", state:"IL", pH:7.4, tds:165, calcium:45, bicarbonate:75, region:"midwest", pfas:6, lead:9.8, nitrate:0.5, violations:5, source:"Lake Michigan", contaminants:"Lead service lines, Microplastics, DBPs" },
  { name:"Houston", state:"TX", pH:7.9, tds:310, calcium:75, bicarbonate:130, region:"south", pfas:17, lead:3.3, nitrate:0.9, violations:3, source:"Lake Livingston / Lake Houston / Trinity River", contaminants:"DBPs, PFAS, HABs, Chloride" },
  { name:"Phoenix", state:"AZ", pH:7.6, tds:420, calcium:95, bicarbonate:155, region:"west", pfas:19, lead:2.1, nitrate:0.7, violations:2, source:"Colorado River / Salt River", contaminants:"PFAS, Chromium-6, DBPs, Arsenic" },
  { name:"Philadelphia", state:"PA", pH:7.1, tds:120, calcium:28, bicarbonate:55, region:"tristate", pfas:17, lead:6.8, nitrate:1.0, violations:6, source:"Delaware and Schuylkill Rivers", contaminants:"Lead, PFAS, Pharmaceuticals, DBPs" },
  { name:"San Antonio", state:"TX", pH:7.7, tds:380, calcium:85, bicarbonate:145, region:"south", pfas:4, lead:1.6, nitrate:0.8, violations:1, source:"Edwards Aquifer", contaminants:"DBPs, Hardness, Radium" },
  { name:"San Diego", state:"CA", pH:7.5, tds:490, calcium:110, bicarbonate:165, region:"west", pfas:15, lead:2.5, nitrate:0.8, violations:3, source:"Colorado River / San Vicente Reservoir", contaminants:"PFAS, DBPs, Chromium-6" },
  { name:"Dallas", state:"TX", pH:7.8, tds:290, calcium:70, bicarbonate:125, region:"south", pfas:12, lead:2.4, nitrate:1.2, violations:2, source:"Lake Ray Hubbard / Lake Tawakoni", contaminants:"DBPs, PFAS, Turbidity" },
  { name:"Miami", state:"FL", pH:7.3, tds:200, calcium:52, bicarbonate:85, region:"fl", pfas:12, lead:4.2, nitrate:1.1, violations:3, source:"Biscayne Aquifer / Hialeah WTP", contaminants:"PFAS, Saltwater Intrusion" },
  { name:"Atlanta", state:"GA", pH:6.9, tds:65, calcium:18, bicarbonate:28, region:"south", pfas:13, lead:3.0, nitrate:0.8, violations:2, source:"Lake Lanier / Chattahoochee River", contaminants:"DBPs, PFAS, Turbidity, HABs" },
  { name:"Seattle", state:"WA", pH:7.0, tds:45, calcium:12, bicarbonate:22, region:"west", pfas:4, lead:2.8, nitrate:0.3, violations:1, source:"Cedar River / Tolt River Watersheds", contaminants:"DBPs, Lead, Cryptosporidium" },
  { name:"Denver", state:"CO", pH:7.6, tds:175, calcium:42, bicarbonate:78, region:"west", pfas:11, lead:2.0, nitrate:0.3, violations:1, source:"South Platte River / Dillon Reservoir", contaminants:"DBPs, Turbidity, PFAS, Manganese" },
  { name:"Boston", state:"MA", pH:7.1, tds:90, calcium:22, bicarbonate:40, region:"northeast", pfas:8, lead:4.7, nitrate:0.4, violations:2, source:"Quabbin and Wachusett Reservoirs", contaminants:"DBPs, Lead, PFAS" },
  { name:"Detroit", state:"MI", pH:7.4, tds:155, calcium:38, bicarbonate:70, region:"midwest", pfas:7, lead:6.1, nitrate:0.4, violations:4, source:"Lake Huron via GLWA pipeline", contaminants:"Lead, DBPs, PFAS" },
  { name:"Nashville", state:"TN", pH:7.5, tds:210, calcium:55, bicarbonate:92, region:"south", pfas:16, lead:2.9, nitrate:0.9, violations:2, source:"Cumberland River", contaminants:"DBPs, PFAS, Turbidity" },
  { name:"Portland OR", state:"OR", pH:7.1, tds:50, calcium:14, bicarbonate:25, region:"west", pfas:4, lead:3.3, nitrate:0.3, violations:3, source:"Bull Run Watershed Mt. Hood", contaminants:"DBPs, Cryptosporidium, Lead" },
  { name:"Las Vegas", state:"NV", pH:8.0, tds:550, calcium:125, bicarbonate:180, region:"west", pfas:10, lead:2.3, nitrate:0.6, violations:2, source:"Colorado River / Lake Mead", contaminants:"PFAS, Chromium-6, DBPs, Perchlorate" },
  { name:"Minneapolis", state:"MN", pH:7.6, tds:200, calcium:52, bicarbonate:88, region:"midwest", pfas:4, lead:2.1, nitrate:0.7, violations:1, source:"Mississippi River", contaminants:"DBPs, Chloride, Microplastics" },
  { name:"New Orleans", state:"LA", pH:7.8, tds:175, calcium:42, bicarbonate:80, region:"south", pfas:29, lead:7.4, nitrate:1.3, violations:8, source:"Mississippi River", contaminants:"DBPs, PFAS, Industrial Runoff, Lead" },
  { name:"Buffalo", state:"NY", pH:7.5, tds:165, calcium:42, bicarbonate:78, region:"ny", pfas:8, lead:14.2, nitrate:0.7, violations:5, source:"Lake Erie", contaminants:"Lead aging pipes, DBPs, Turbidity" },
  { name:"Rochester", state:"NY", pH:7.4, tds:145, calcium:38, bicarbonate:68, region:"ny", pfas:9, lead:4.6, nitrate:0.6, violations:3, source:"Lake Ontario", contaminants:"DBPs, Lead, Microplastics" },
  { name:"Syracuse", state:"NY", pH:7.3, tds:130, calcium:34, bicarbonate:62, region:"ny", pfas:4, lead:2.0, nitrate:0.5, violations:1, source:"Skaneateles Lake / Otisco Lake", contaminants:"DBPs, Turbidity" },
  { name:"Albany", state:"NY", pH:7.2, tds:85, calcium:20, bicarbonate:38, region:"ny", pfas:6, lead:3.1, nitrate:0.4, violations:2, source:"Hudson River / Alcove Reservoir", contaminants:"DBPs, Lead, Industrial Legacy" },
  { name:"Yonkers", state:"NY", pH:7.2, tds:55, calcium:15, bicarbonate:32, region:"tristate", pfas:10, lead:6.8, nitrate:0.5, violations:4, source:"Catskill Delaware Aqueduct NYC DEP", contaminants:"Lead, DBPs, PFAS" },
  { name:"Long Island Nassau", state:"NY", pH:7.4, tds:175, calcium:44, bicarbonate:80, region:"tristate", pfas:120, lead:2.9, nitrate:2.1, violations:9, source:"Upper Glacial and Magothy Aquifers", contaminants:"PFAS CRISIS, Nitrates, Industrial Legacy" },
  { name:"Long Island Suffolk", state:"NY", pH:7.3, tds:155, calcium:38, bicarbonate:70, region:"tristate", pfas:85, lead:2.4, nitrate:3.8, violations:11, source:"Upper Glacial and Magothy Aquifers", contaminants:"PFAS CRISIS, Nitrates, Pesticides" },
  { name:"Westchester", state:"NY", pH:7.2, tds:60, calcium:16, bicarbonate:34, region:"tristate", pfas:8, lead:4.1, nitrate:0.6, violations:3, source:"Catskill Delaware Watershed NYC DEP", contaminants:"Lead, DBPs, PFAS" },
  { name:"Poughkeepsie", state:"NY", pH:7.3, tds:95, calcium:24, bicarbonate:45, region:"ny", pfas:7, lead:3.5, nitrate:0.8, violations:2, source:"Hudson River", contaminants:"DBPs, Industrial discharge, Lead" },
  { name:"Newburgh", state:"NY", pH:7.1, tds:80, calcium:20, bicarbonate:38, region:"ny", pfas:140, lead:4.2, nitrate:1.1, violations:8, source:"Lake Washington / Hudson River", contaminants:"PFAS CRISIS, Lead, DBPs" },
  { name:"Newark", state:"NJ", pH:7.1, tds:55, calcium:13, bicarbonate:28, region:"tristate", pfas:22, lead:55.0, nitrate:1.2, violations:12, source:"Passaic River / Pequannock Watershed", contaminants:"Lead CRISIS, PFAS, DBPs" },
  { name:"Jersey City", state:"NJ", pH:7.2, tds:60, calcium:15, bicarbonate:30, region:"tristate", pfas:14, lead:8.9, nitrate:0.8, violations:5, source:"Passaic River / Boonton Reservoir", contaminants:"Lead, DBPs, Microplastics" },
  { name:"Trenton", state:"NJ", pH:7.4, tds:220, calcium:55, bicarbonate:95, region:"nj", pfas:9, lead:7.2, nitrate:1.4, violations:4, source:"Delaware River", contaminants:"Lead, DBPs, PFAS" },
  { name:"Camden", state:"NJ", pH:7.2, tds:135, calcium:32, bicarbonate:58, region:"nj", pfas:31, lead:21.4, nitrate:1.1, violations:13, source:"Delaware River", contaminants:"Lead CRISIS, PFAS, DBPs, Industrial" },
  { name:"Paterson", state:"NJ", pH:7.1, tds:65, calcium:16, bicarbonate:30, region:"tristate", pfas:28, lead:18.3, nitrate:0.9, violations:10, source:"Passaic River", contaminants:"Lead, PFAS, Industrial discharge" },
  { name:"Elizabeth", state:"NJ", pH:7.2, tds:97, calcium:24, bicarbonate:45, region:"tristate", pfas:38, lead:9.4, nitrate:1.2, violations:7, source:"Passaic / Rahway River", contaminants:"PFAS, Lead, Industrial corridor" },
  { name:"East Orange", state:"NJ", pH:7.8, tds:485, calcium:110, bicarbonate:165, region:"tristate", pfas:12, lead:3.3, nitrate:0.8, violations:2, source:"Oradell Reservoir / Hackensack River", contaminants:"DBPs, Lead, PFAS" },
  { name:"Edison", state:"NJ", pH:7.5, tds:185, calcium:46, bicarbonate:84, region:"nj", pfas:19, lead:3.6, nitrate:1.1, violations:3, source:"Raritan River / Brunswick Aquifer", contaminants:"PFAS, DBPs, Industrial" },
  { name:"Woodbridge", state:"NJ", pH:7.4, tds:170, calcium:42, bicarbonate:78, region:"nj", pfas:14, lead:2.8, nitrate:1.0, violations:2, source:"Raritan River / Local Wells", contaminants:"PFAS, DBPs" },
  { name:"Toms River", state:"NJ", pH:7.3, tds:115, calcium:28, bicarbonate:52, region:"nj", pfas:42, lead:2.1, nitrate:0.9, violations:5, source:"Cohansey / Atlantic City Aquifer", contaminants:"PFAS, DBPs, Industrial legacy" },
  { name:"Hackensack", state:"NJ", pH:7.2, tds:75, calcium:18, bicarbonate:35, region:"tristate", pfas:12, lead:3.3, nitrate:0.7, violations:2, source:"Oradell Reservoir / Hackensack River", contaminants:"DBPs, Lead, PFAS" },
  { name:"Princeton", state:"NJ", pH:7.3, tds:130, calcium:32, bicarbonate:58, region:"nj", pfas:8, lead:2.4, nitrate:0.9, violations:2, source:"Delaware and Raritan Canal", contaminants:"DBPs, PFAS, Pharmaceuticals" },
  { name:"Bridgeport", state:"CT", pH:7.2, tds:110, calcium:27, bicarbonate:50, region:"ct", pfas:16, lead:9.2, nitrate:0.7, violations:5, source:"Aquarion Water Co Reservoirs", contaminants:"Lead, PFAS, DBPs" },
  { name:"New Haven", state:"CT", pH:7.1, tds:95, calcium:24, bicarbonate:44, region:"ct", pfas:14, lead:7.3, nitrate:0.6, violations:4, source:"Lake Saltonstall / Lake Whitney", contaminants:"DBPs, Lead, PFAS" },
  { name:"Hartford", state:"CT", pH:7.0, tds:75, calcium:18, bicarbonate:32, region:"ct", pfas:9, lead:5.1, nitrate:0.5, violations:3, source:"Metropolitan District Reservoirs", contaminants:"DBPs, Lead, PFAS" },
  { name:"Stamford", state:"CT", pH:7.1, tds:51, calcium:13, bicarbonate:26, region:"ct", pfas:21, lead:6.4, nitrate:0.6, violations:3, source:"Aquarion Water Reservoirs", contaminants:"PFAS, Lead, DBPs" },
  { name:"Waterbury", state:"CT", pH:7.2, tds:105, calcium:26, bicarbonate:48, region:"ct", pfas:6, lead:8.8, nitrate:0.7, violations:6, source:"Wigwam Reservoir / Mad River", contaminants:"Lead, DBPs, PFAS" },
  { name:"Norwalk", state:"CT", pH:7.1, tds:88, calcium:22, bicarbonate:40, region:"ct", pfas:8, lead:4.2, nitrate:0.5, violations:2, source:"Aquarion Reservoirs", contaminants:"Lead, DBPs, PFAS" },
  { name:"Danbury", state:"CT", pH:7.0, tds:70, calcium:17, bicarbonate:30, region:"ct", pfas:11, lead:3.9, nitrate:0.5, violations:2, source:"Lake Candlewood / Marginal areas", contaminants:"PFAS, DBPs, Lead" },
  { name:"Greenwich", state:"CT", pH:7.1, tds:60, calcium:15, bicarbonate:28, region:"ct", pfas:14, lead:4.1, nitrate:0.5, violations:2, source:"Aquarion Water Reservoirs", contaminants:"PFAS, Lead, DBPs" },
  { name:"Allentown", state:"PA", pH:7.6, tds:222, calcium:56, bicarbonate:105, region:"lehigh", pfas:13, lead:3.8, nitrate:1.2, violations:3, source:"Little Lehigh Creek / Local Reservoirs", contaminants:"PFAS, DBPs, Lead" },
  { name:"Bethlehem", state:"PA", pH:7.2, tds:17, calcium:4, bicarbonate:14, region:"lehigh", pfas:11, lead:3.5, nitrate:0.8, violations:2, source:"Little Lehigh / Saucon Creek", contaminants:"PFAS, DBPs, Lead" },
  { name:"Easton", state:"PA", pH:7.1, tds:46, calcium:11, bicarbonate:24, region:"lehigh", pfas:7, lead:3.0, nitrate:0.7, violations:1, source:"Delaware River / Bushkill Creek", contaminants:"DBPs, Lead, PFAS" },
  { name:"Reading", state:"PA", pH:7.4, tds:130, calcium:32, bicarbonate:60, region:"pa", pfas:21, lead:5.7, nitrate:1.1, violations:5, source:"Schuylkill River / Neversink Reservoir", contaminants:"PFAS, Lead, DBPs" },
  { name:"Lancaster", state:"PA", pH:7.5, tds:163, calcium:41, bicarbonate:75, region:"pa", pfas:4, lead:2.1, nitrate:1.8, violations:2, source:"Conestoga River / Pequea Creek", contaminants:"Nitrates, DBPs, Agricultural runoff" },
  { name:"Harrisburg", state:"PA", pH:7.4, tds:137, calcium:34, bicarbonate:62, region:"pa", pfas:6, lead:2.6, nitrate:0.9, violations:2, source:"Susquehanna River", contaminants:"DBPs, PFAS, Industrial" },
  { name:"Scranton", state:"PA", pH:7.3, tds:115, calcium:28, bicarbonate:52, region:"pa", pfas:5, lead:4.2, nitrate:0.8, violations:3, source:"Elmhurst Reservoir / Roaring Brook", contaminants:"DBPs, Lead, PFAS" },
  { name:"Pittsburgh", state:"PA", pH:7.4, tds:130, calcium:32, bicarbonate:58, region:"pa", pfas:8, lead:4.9, nitrate:1.2, violations:4, source:"Allegheny and Monongahela Rivers", contaminants:"PFAS, DBPs, Industrial Runoff, Lead" },
  { name:"York", state:"PA", pH:7.3, tds:89, calcium:22, bicarbonate:42, region:"pa", pfas:5, lead:2.8, nitrate:1.1, violations:2, source:"Codorus Creek / Local Reservoirs", contaminants:"DBPs, Lead, Agricultural runoff" },
  { name:"Wilkes-Barre", state:"PA", pH:7.3, tds:108, calcium:27, bicarbonate:50, region:"pa", pfas:5, lead:3.1, nitrate:0.7, violations:2, source:"Susquehanna River / Local Reservoirs", contaminants:"DBPs, Lead, Industrial legacy" },
  { name:"Kutztown", state:"PA", pH:7.4, tds:145, calcium:36, bicarbonate:66, region:"lehigh", pfas:6, lead:2.4, nitrate:1.0, violations:1, source:"Alburtis Limestone Aquifer", contaminants:"DBPs, Agricultural runoff" },
  { name:"Horsham Township", state:"PA", pH:7.2, tds:180, calcium:38, bicarbonate:72, region:"pa", pfas:1100, lead:2.8, nitrate:0.9, violations:7, source:"Horsham Township Wells / NAS Willow Grove", contaminants:"PFAS CRISIS #1 IN USA — 1100 ppt NAS Willow Grove military contamination" },
  { name:"Warminster Township", state:"PA", pH:7.2, tds:165, calcium:34, bicarbonate:68, region:"pa", pfas:780, lead:2.6, nitrate:0.8, violations:6, source:"Naval Air Warfare Center Wells", contaminants:"PFAS CRISIS — 780 ppt Naval Air Warfare Center contamination" },
  { name:"Tampa", state:"FL", pH:7.8, tds:285, calcium:68, bicarbonate:120, region:"fl", pfas:18, lead:3.8, nitrate:0.9, violations:2, source:"Tampa Bypass Canal / Hillsborough River", contaminants:"DBPs, PFAS, HABs" },
  { name:"Orlando", state:"FL", pH:7.6, tds:245, calcium:58, bicarbonate:105, region:"fl", pfas:6, lead:2.1, nitrate:0.8, violations:1, source:"Floridan Aquifer System", contaminants:"Radium, DBPs" },
  { name:"Jacksonville", state:"FL", pH:7.5, tds:190, calcium:46, bicarbonate:88, region:"fl", pfas:8, lead:1.9, nitrate:0.7, violations:1, source:"Floridan Aquifer", contaminants:"DBPs, PFAS, Radium" },
  { name:"Fort Lauderdale", state:"FL", pH:7.9, tds:310, calcium:74, bicarbonate:130, region:"fl", pfas:22, lead:5.1, nitrate:1.2, violations:4, source:"Everglades / Canal System", contaminants:"PFAS, DBPs, Saltwater Intrusion" },
  { name:"Tallahassee", state:"FL", pH:7.2, tds:125, calcium:30, bicarbonate:58, region:"fl", pfas:4, lead:1.4, nitrate:0.6, violations:0, source:"Floridan Aquifer", contaminants:"DBPs, Radium" },
  { name:"Gainesville", state:"FL", pH:7.4, tds:168, calcium:42, bicarbonate:78, region:"fl", pfas:3, lead:1.1, nitrate:0.5, violations:0, source:"Floridan Aquifer", contaminants:"DBPs minimal" },
  { name:"Sarasota", state:"FL", pH:7.7, tds:260, calcium:62, bicarbonate:112, region:"fl", pfas:5, lead:1.7, nitrate:0.7, violations:1, source:"Peace River / Floridan Aquifer", contaminants:"DBPs, HABs, Saltwater risk" },
  { name:"Cape Coral", state:"FL", pH:7.8, tds:290, calcium:70, bicarbonate:125, region:"fl", pfas:7, lead:2.0, nitrate:0.8, violations:1, source:"Floridan Aquifer plus Reverse Osmosis", contaminants:"DBPs, Saltwater intrusion risk" },
  { name:"St Petersburg", state:"FL", pH:7.6, tds:240, calcium:56, bicarbonate:100, region:"fl", pfas:14, lead:3.2, nitrate:0.9, violations:2, source:"Tampa Bay Watershed", contaminants:"DBPs, PFAS, HABs" },
  { name:"Pensacola", state:"FL", pH:7.3, tds:145, calcium:36, bicarbonate:68, region:"fl", pfas:9, lead:2.1, nitrate:0.6, violations:1, source:"Pensacola Bay Watershed", contaminants:"DBPs, PFAS, Military legacy" },
  { name:"Fayetteville", state:"NC", pH:7.2, tds:125, calcium:30, bicarbonate:56, region:"nc", pfas:700, lead:4.8, nitrate:1.1, violations:7, source:"Cape Fear River", contaminants:"PFAS CRISIS — 700 ppt GenX from Chemours — national emergency" },
  { name:"Columbus", state:"OH", pH:7.5, tds:235, calcium:58, bicarbonate:102, region:"oh", pfas:9, lead:2.4, nitrate:1.8, violations:2, source:"Scioto River / Hoover Reservoir", contaminants:"HABs, PFAS, DBPs" },
  { name:"Cleveland", state:"OH", pH:7.4, tds:195, calcium:48, bicarbonate:88, region:"oh", pfas:11, lead:8.7, nitrate:0.9, violations:5, source:"Lake Erie", contaminants:"Lead aging pipes, HABs, Chloride" },
  { name:"Cincinnati", state:"OH", pH:7.6, tds:260, calcium:64, bicarbonate:112, region:"oh", pfas:34, lead:4.1, nitrate:1.3, violations:3, source:"Ohio River", contaminants:"PFAS, DBPs, Industrial discharge" },
  { name:"Toledo", state:"OH", pH:7.5, tds:220, calcium:54, bicarbonate:98, region:"oh", pfas:7, lead:3.3, nitrate:0.8, violations:6, source:"Lake Erie Maumee Bay", contaminants:"HABs 2014 crisis, DBPs, Chloride" },
  { name:"Akron", state:"OH", pH:7.3, tds:175, calcium:42, bicarbonate:80, region:"oh", pfas:6, lead:5.9, nitrate:0.9, violations:2, source:"Portage Lakes / Cuyahoga River", contaminants:"Lead, DBPs, HABs" },
  { name:"Dayton", state:"OH", pH:7.4, tds:205, calcium:50, bicarbonate:92, region:"oh", pfas:88, lead:2.6, nitrate:1.1, violations:4, source:"Great Miami River Aquifer", contaminants:"PFAS CRISIS — 88 ppt, DBPs, Industrial" },
  { name:"Youngstown", state:"OH", pH:7.2, tds:155, calcium:38, bicarbonate:72, region:"oh", pfas:5, lead:12.4, nitrate:0.8, violations:8, source:"Berlin Reservoir / Meander Creek", contaminants:"Lead, DBPs, Industrial legacy" },
  { name:"Canton", state:"OH", pH:7.4, tds:190, calcium:46, bicarbonate:85, region:"oh", pfas:5, lead:3.8, nitrate:0.9, violations:3, source:"Nimisila Reservoir / Local Sources", contaminants:"DBPs, Lead, Industrial" },
  { name:"Charlotte", state:"NC", pH:7.2, tds:125, calcium:30, bicarbonate:56, region:"nc", pfas:16, lead:3.5, nitrate:1.4, violations:2, source:"Lake Norman / Mountain Island Lake", contaminants:"PFAS GenX, DBPs, Turbidity" },
  { name:"Raleigh", state:"NC", pH:7.1, tds:95, calcium:22, bicarbonate:42, region:"nc", pfas:7, lead:2.2, nitrate:1.6, violations:1, source:"Falls Lake / Lake Benson", contaminants:"DBPs, Turbidity, Cyanotoxins" },
  { name:"Greensboro", state:"NC", pH:7.2, tds:110, calcium:27, bicarbonate:50, region:"nc", pfas:5, lead:1.8, nitrate:1.1, violations:1, source:"Lake Townsend / Reedy Fork", contaminants:"DBPs, Turbidity" },
  { name:"Durham", state:"NC", pH:7.1, tds:100, calcium:24, bicarbonate:45, region:"nc", pfas:12, lead:2.7, nitrate:1.3, violations:2, source:"Falls Lake / Lake Michie", contaminants:"PFAS, DBPs, Turbidity" },
  { name:"Winston-Salem", state:"NC", pH:7.3, tds:135, calcium:33, bicarbonate:62, region:"nc", pfas:4, lead:1.5, nitrate:0.9, violations:0, source:"Salem Lake / Yadkin River", contaminants:"DBPs, Turbidity" },
  { name:"Wilmington", state:"NC", pH:7.4, tds:155, calcium:38, bicarbonate:70, region:"nc", pfas:180, lead:3.9, nitrate:1.2, violations:5, source:"Cape Fear River / Castle Hayne Aquifer", contaminants:"PFAS CRISIS — 180 ppt GenX, DBPs" },
  { name:"Asheville", state:"NC", pH:6.9, tds:65, calcium:16, bicarbonate:28, region:"nc", pfas:3, lead:1.4, nitrate:0.5, violations:0, source:"North Fork Reservoir / Swannanoa River", contaminants:"DBPs minimal, Soft corrosive water" },
  { name:"Columbia", state:"SC", pH:7.2, tds:115, calcium:27, bicarbonate:52, region:"sc", pfas:6, lead:3.1, nitrate:1.5, violations:2, source:"Lake Murray / Saluda River", contaminants:"DBPs, Turbidity, Nutrients" },
  { name:"Charleston", state:"SC", pH:7.5, tds:185, calcium:44, bicarbonate:82, region:"sc", pfas:8, lead:2.8, nitrate:0.8, violations:3, source:"Edisto River / Bushy Park", contaminants:"DBPs, HABs, Saltwater Intrusion" },
  { name:"Greenville", state:"SC", pH:7.1, tds:88, calcium:20, bicarbonate:40, region:"sc", pfas:3, lead:1.4, nitrate:0.7, violations:0, source:"North Saluda Reservoir / Table Rock", contaminants:"DBPs minimal" },
  { name:"Rock Hill", state:"SC", pH:7.3, tds:130, calcium:32, bicarbonate:58, region:"sc", pfas:14, lead:2.5, nitrate:1.0, violations:1, source:"Lake Wylie / Catawba River", contaminants:"PFAS, DBPs, Nutrients" },
  { name:"Spartanburg", state:"SC", pH:7.2, tds:110, calcium:26, bicarbonate:50, region:"sc", pfas:4, lead:1.7, nitrate:0.8, violations:1, source:"Lake Blalock / Pacolet River", contaminants:"DBPs, Turbidity" },
  { name:"Myrtle Beach", state:"SC", pH:7.5, tds:195, calcium:47, bicarbonate:88, region:"sc", pfas:9, lead:3.0, nitrate:1.1, violations:2, source:"Pee Dee River / Waccamaw River", contaminants:"DBPs, HABs, Saltwater risk" },
  { name:"Hilton Head", state:"SC", pH:7.4, tds:170, calcium:40, bicarbonate:76, region:"sc", pfas:2, lead:1.1, nitrate:0.5, violations:0, source:"Floridan Aquifer artesian", contaminants:"DBPs minimal — one of cleanest in SC" },
  { name:"Summerville", state:"SC", pH:7.3, tds:140, calcium:34, bicarbonate:64, region:"sc", pfas:6, lead:2.1, nitrate:0.9, violations:1, source:"Edisto River / Local Aquifer", contaminants:"DBPs, Turbidity" },
  { name:"Baltimore", state:"MD", pH:7.4, tds:145, calcium:35, bicarbonate:68, region:"northeast", pfas:9, lead:7.6, nitrate:0.8, violations:5, source:"Loch Raven and Prettyboy Reservoirs", contaminants:"DBPs, Lead, Chromium-6, HABs" },
  { name:"Washington DC", state:"DC", pH:7.3, tds:130, calcium:32, bicarbonate:62, region:"northeast", pfas:8, lead:5.8, nitrate:0.5, violations:3, source:"Potomac River", contaminants:"Lead historical crisis, DBPs, PFAS" },
  { name:"Jackson", state:"MS", pH:7.1, tds:95, calcium:22, bicarbonate:42, region:"south", pfas:6, lead:37.8, nitrate:1.4, violations:22, source:"Ross Barnett Reservoir / Pearl River", contaminants:"Lead CRISIS — 37.8 ppb, DBPs, Turbidity, Infrastructure failure" },
  { name:"Flint", state:"MI", pH:7.2, tds:110, calcium:26, bicarbonate:48, region:"midwest", pfas:8, lead:22.0, nitrate:0.6, violations:9, source:"GLWA Lake Huron via Detroit", contaminants:"Lead CRISIS legacy — 22 ppb, Copper, DBPs" },
  { name:"Benton Harbor", state:"MI", pH:7.1, tds:95, calcium:22, bicarbonate:44, region:"midwest", pfas:11, lead:55.0, nitrate:0.8, violations:18, source:"Lake Michigan / Whirlpool Corp wells", contaminants:"Lead CRISIS — 55 ppb highest in database, Industrial contamination" },
  { name:"Honolulu", state:"HI", pH:7.4, tds:180, calcium:44, bicarbonate:82, region:"west", pfas:350, lead:2.4, nitrate:1.8, violations:11, source:"Oahu Basal Aquifer volcanic rock", contaminants:"PFAS CRISIS — 350 ppt Red Hill Navy fuel leak" },
  { name:"Milwaukee", state:"WI", pH:7.3, tds:165, calcium:40, bicarbonate:75, region:"midwest", pfas:5, lead:11.3, nitrate:0.8, violations:4, source:"Lake Michigan", contaminants:"Lead aging pipes, DBPs, PFAS" },
  { name:"Cape Cod", state:"MA", pH:7.0, tds:85, calcium:20, bicarbonate:38, region:"northeast", pfas:320, lead:2.8, nitrate:2.1, violations:8, source:"Cape Cod Aquifer glacial outwash", contaminants:"PFAS CRISIS — 320 ppt, Nitrates, Industrial" },
  { name:"Colorado Springs", state:"CO", pH:7.4, tds:155, calcium:38, bicarbonate:72, region:"west", pfas:110, lead:1.9, nitrate:0.6, violations:4, source:"Pikes Peak Snowmelt / Fryingpan-Arkansas", contaminants:"PFAS CRISIS — 110 ppt military base" },
  { name:"Hoosick Falls", state:"NY", pH:7.1, tds:75, calcium:18, bicarbonate:35, region:"ny", pfas:540, lead:2.4, nitrate:0.8, violations:6, source:"Hoosic River Aquifer", contaminants:"PFAS CRISIS — 540 ppt Saint-Gobain industrial discharge" },
  { name:"San Francisco", state:"CA", pH:7.3, tds:65, calcium:15, bicarbonate:30, region:"west", pfas:5, lead:3.1, nitrate:0.3, violations:1, source:"Hetch Hetchy Reservoir Sierra Nevada", contaminants:"DBPs, Lead older plumbing, Microplastics" },
  { name:"San Jose", state:"CA", pH:7.6, tds:220, calcium:54, bicarbonate:98, region:"west", pfas:16, lead:2.1, nitrate:1.2, violations:2, source:"Santa Clara Valley Water District", contaminants:"PFAS, DBPs, Chromium-6" },
  { name:"Sacramento", state:"CA", pH:7.5, tds:195, calcium:48, bicarbonate:88, region:"west", pfas:21, lead:2.4, nitrate:1.1, violations:2, source:"Sacramento River / American River", contaminants:"PFAS, DBPs, Agricultural runoff" },
  { name:"Portland ME", state:"ME", pH:7.0, tds:45, calcium:11, bicarbonate:22, region:"northeast", pfas:3, lead:1.4, nitrate:0.3, violations:0, source:"Sebago Lake", contaminants:"DBPs, Microplastics, Turbidity" },
  { name:"Providence", state:"RI", pH:7.2, tds:95, calcium:23, bicarbonate:44, region:"northeast", pfas:7, lead:5.5, nitrate:0.5, violations:2, source:"Scituate Reservoir", contaminants:"DBPs, PFAS, Lead" },
  { name:"Louisville", state:"KY", pH:7.5, tds:195, calcium:48, bicarbonate:88, region:"south", pfas:11, lead:4.8, nitrate:1.2, violations:3, source:"Ohio River", contaminants:"DBPs, PFAS, Lead, Industrial" },
  { name:"Indianapolis", state:"IN", pH:7.4, tds:175, calcium:44, bicarbonate:80, region:"midwest", pfas:11, lead:3.4, nitrate:1.3, violations:3, source:"White River / Eagle Creek Reservoir", contaminants:"DBPs, HABs, PFAS" },
  { name:"Kansas City", state:"MO", pH:7.5, tds:205, calcium:50, bicarbonate:92, region:"midwest", pfas:9, lead:2.8, nitrate:2.1, violations:2, source:"Missouri River", contaminants:"DBPs, Turbidity, Nitrates, PFAS" },
  { name:"St Louis", state:"MO", pH:7.4, tds:195, calcium:48, bicarbonate:88, region:"midwest", pfas:12, lead:5.3, nitrate:1.5, violations:4, source:"Missouri and Mississippi Rivers", contaminants:"DBPs, Lead, PFAS, Turbidity" },
  { name:"Des Moines", state:"IA", pH:7.3, tds:165, calcium:40, bicarbonate:75, region:"midwest", pfas:4, lead:1.8, nitrate:11.2, violations:5, source:"Raccoon and Des Moines Rivers", contaminants:"Nitrates CRISIS — 11.2 ppm exceeds EPA MCL, Atrazine, DBPs" },
  { name:"Wichita", state:"KS", pH:7.5, tds:210, calcium:52, bicarbonate:95, region:"midwest", pfas:62, lead:2.5, nitrate:1.4, violations:3, source:"Equus Beds Aquifer / Arkansas River", contaminants:"PFAS — 62 ppt McConnell AFB, DBPs, Radium" },
  { name:"Omaha", state:"NE", pH:7.4, tds:185, calcium:46, bicarbonate:84, region:"midwest", pfas:5, lead:2.0, nitrate:3.8, violations:1, source:"Missouri River / Platte River Aquifer", contaminants:"DBPs, Nitrates, Atrazine" },
  { name:"Baton Rouge", state:"LA", pH:7.7, tds:195, calcium:48, bicarbonate:88, region:"south", pfas:22, lead:3.8, nitrate:1.2, violations:4, source:"Mississippi River", contaminants:"PFAS, DBPs, Industrial discharge" },
  { name:"Richmond", state:"VA", pH:7.3, tds:135, calcium:33, bicarbonate:62, region:"south", pfas:16, lead:3.2, nitrate:0.9, violations:2, source:"James River", contaminants:"DBPs, PFAS, Industrial" },
  { name:"Virginia Beach", state:"VA", pH:7.4, tds:155, calcium:38, bicarbonate:72, region:"south", pfas:44, lead:3.8, nitrate:1.1, violations:4, source:"Lake Gaston / Local Aquifers", contaminants:"PFAS — 44 ppt Military bases, DBPs" },
  { name:"Norfolk", state:"VA", pH:7.3, tds:145, calcium:35, bicarbonate:68, region:"south", pfas:38, lead:3.6, nitrate:0.9, violations:3, source:"Lake Prince / Western Branch Reservoir", contaminants:"PFAS — 38 ppt Military, DBPs, Lead" },
  { name:"Memphis", state:"TN", pH:7.3, tds:125, calcium:30, bicarbonate:58, region:"south", pfas:9, lead:1.8, nitrate:0.5, violations:1, source:"Memphis Sand Aquifer", contaminants:"DBPs minimal — excellent aquifer source" },
  { name:"Salt Lake City", state:"UT", pH:7.5, tds:195, calcium:48, bicarbonate:88, region:"west", pfas:22, lead:1.8, nitrate:0.8, violations:1, source:"Salt Lake City Watershed Wasatch Mountains", contaminants:"PFAS, DBPs, Minerals" },
  { name:"Albuquerque", state:"NM", pH:7.4, tds:175, calcium:44, bicarbonate:80, region:"west", pfas:48, lead:1.8, nitrate:1.2, violations:2, source:"Rio Grande / San Juan-Chama / Santa Fe Aquifer", contaminants:"PFAS, DBPs, Arsenic" },
  { name:"Tucson", state:"AZ", pH:7.5, tds:205, calcium:50, bicarbonate:92, region:"west", pfas:24, lead:1.7, nitrate:1.1, violations:2, source:"Tucson Aquifer / Colorado River CAP", contaminants:"PFAS, DBPs, Arsenic" },
  { name:"El Paso", state:"TX", pH:7.6, tds:215, calcium:52, bicarbonate:96, region:"south", pfas:95, lead:2.0, nitrate:1.3, violations:3, source:"Hueco Bolson Aquifer / Rio Grande", contaminants:"PFAS — 95 ppt Military, DBPs, Arsenic" },
  { name:"Austin", state:"TX", pH:7.4, tds:185, calcium:46, bicarbonate:84, region:"south", pfas:8, lead:1.9, nitrate:0.9, violations:1, source:"Lake Travis / Lake Austin Colorado River", contaminants:"DBPs, PFAS, HABs" },
  { name:"Fort Worth", state:"TX", pH:7.6, tds:210, calcium:52, bicarbonate:95, region:"south", pfas:15, lead:2.2, nitrate:1.1, violations:2, source:"Eagle Mountain Lake / Cedar Creek Reservoir", contaminants:"PFAS, DBPs, Turbidity" },
];

export const GLOSSARY = [
  { term:"LSI", full:"Langelier Saturation Index", icon:"🔬", color:"#0369a1", def:"A scientific formula measuring whether water is corrosive, balanced, or scale-forming. Negative LSI water pulls calcium and magnesium from your body. Ideal range is -0.2 to +0.2.", example:"Dasani LSI -1.8 very aggressive. Evian LSI +0.1 balanced." },
  { term:"TDS", full:"Total Dissolved Solids", icon:"💧", color:"#0369a1", def:"Total concentration of dissolved minerals in water measured in mg/L. Higher TDS from natural minerals is generally positive for health.", example:"NYC tap 50 mg/L very low. Gerolsteiner 2527 mg/L very high mineral-rich." },
  { term:"pH", full:"Potential of Hydrogen", icon:"⚗️", color:"#0369a1", def:"Scale from 0-14 measuring acidity or alkalinity. 7.0 is neutral. Ideal drinking water pH is 7.0-8.5. Below 6.5 is aggressive to teeth and body.", example:"Aquafina pH 6.0 acidic. Evian pH 7.2 ideal. Icelandic Glacial pH 8.4 alkaline." },
  { term:"PFAS", full:"Per and Polyfluoroalkyl Substances", icon:"☢️", color:"#dc2626", def:"Man-made forever chemicals that do not break down. Linked to cancer, thyroid disease, immune suppression, and developmental issues. EPA health advisory is 4 ppt. Many US cities exceed this dramatically.", example:"Horsham PA 1100 ppt. Fayetteville NC 700 ppt. EPA limit 4 ppt." },
  { term:"Lead", full:"Lead Contamination", icon:"🔴", color:"#dc2626", def:"Heavy metal with no safe level of exposure. Causes irreversible neurological damage especially in children under 6. Sources are usually lead service lines or older plumbing installed before 1986.", example:"EPA action level 15 ppb. Newark NJ 55 ppb. Benton Harbor MI 55 ppb." },
  { term:"Nitrate", full:"Nitrate Contamination", icon:"🌾", color:"#ca8a04", def:"Primarily from agricultural fertilizer runoff. EPA maximum 10 ppm. Dangerous for infants under 6 months causing blue baby syndrome where blood cannot carry oxygen.", example:"Des Moines IA 11.2 ppm — exceeds EPA maximum of 10 ppm." },
  { term:"Calcium", full:"Calcium Hardness", icon:"🦴", color:"#0369a1", def:"Essential mineral for bone density, muscle contraction, nerve transmission, and heart rhythm. WHO recommends 50-100 mg/L minimum in drinking water.", example:"Contrex 486 mg/L exceptional. Aquafina 0 mg/L none at all." },
  { term:"Magnesium", full:"Magnesium Content", icon:"⚡", color:"#0369a1", def:"Master mineral involved in 300 plus enzymatic reactions. Regulates sleep, stress, muscle function, blood sugar, and heart rhythm. Up to 50% of Americans are deficient.", example:"Apollinaris 130 mg/L highest available. Smartwater 0 mg/L none." },
  { term:"Bicarbonate", full:"Bicarbonate Alkalinity", icon:"🌊", color:"#0369a1", def:"Natural buffer that neutralizes acidity in water and in your body. Higher bicarbonate protects tooth enamel and is key in LSI calculation.", example:"Gerolsteiner 1816 mg/L. Dasani 0 mg/L." },
  { term:"DBPs", full:"Disinfection Byproducts", icon:"🧪", color:"#7c3aed", def:"Chemicals formed when chlorine used to disinfect water reacts with natural organic matter. Trihalomethanes and haloacetic acids are DBPs linked to cancer risk at high long-term exposure.", example:"Most surface water systems produce some DBPs. Higher in summer when organic matter is elevated." },
  { term:"HABs", full:"Harmful Algal Blooms", icon:"🌿", color:"#16a34a", def:"Explosive growth of cyanobacteria in warm nutrient-rich water. Produce cyanotoxins that cause liver damage, neurological effects, and skin irritation. Climate change is accelerating HABs nationwide.", example:"Toledo OH 2014 — HAB in Lake Erie left 500,000 people without safe water for 3 days." },
  { term:"CCR", full:"Consumer Confidence Report", icon:"📋", color:"#0369a1", def:"Annual water quality report every public utility must provide free by law. Lists every contaminant detected, its level, and the legal limit. You have the right to this report.", example:"Call your utility and say: I am requesting my Consumer Confidence Report under the Safe Drinking Water Act." },
  { term:"NSF 53", full:"NSF International Standard 53", icon:"✅", color:"#16a34a", def:"Certification standard for water filters that remove health-related contaminants including lead. Only NSF 53 certified filters are verified to remove lead. Standard carbon filters are NOT certified for lead.", example:"Clearly Filtered and Aquasana AQ-5200 are NSF 53 certified. Standard Brita is NOT." },
  { term:"Reverse Osmosis", full:"Reverse Osmosis Filtration", icon:"🔧", color:"#0369a1", def:"Filtration technology that forces water through a semipermeable membrane removing 95-99% of contaminants including PFAS, lead, nitrates, arsenic, and most dissolved solids.", example:"APEC ROES-50 removes 99% of PFAS and lead. Cost approximately 200 dollars installed." },
  { term:"Hardness", full:"Water Hardness", icon:"💎", color:"#0369a1", def:"Measure of calcium and magnesium content. Soft water 0-75 ppm is low in beneficial minerals. Hard water 150 plus ppm contains more minerals but may cause scale buildup.", example:"Bethlehem PA very soft 17 ppm. Allentown PA moderately hard 222 ppm." },
  { term:"WHO Standard", full:"World Health Organization Guideline", icon:"🌍", color:"#0369a1", def:"WHO recommends drinking water contain minimum 50-100 mg/L calcium and 25-50 mg/L magnesium. Most bottled waters fail this standard completely.", example:"Only 12 of the 40 brands Walter tracks meet WHO mineral minimums." },
  { term:"LSL", full:"Lead Service Lines", icon:"🚰", color:"#dc2626", def:"Pipes made of lead connecting the water main to your home. Installed widely before 1986. Estimated 9-12 million lead service lines still in use across the US. Primary source of lead contamination.", example:"Chicago has approximately 400,000 lead service lines — largest inventory in the US." },
  { term:"Chromium-6", full:"Hexavalent Chromium", icon:"⚗️", color:"#7c3aed", def:"Toxic form of chromium linked to cancer. Naturally occurring in some groundwater but also from industrial discharge. Featured in the Erin Brockovich case. No federal MCL currently set specifically for Chromium-6.", example:"Los Angeles, Phoenix, and San Jose all have detected Chromium-6 in tap water." },
  { term:"Atrazine", full:"Atrazine Herbicide", icon:"🌾", color:"#ca8a04", def:"Most widely used herbicide in the US applied primarily to corn fields. Washes into rivers and groundwater throughout the Midwest. Linked to endocrine disruption and developmental issues. EPA limit 3 ppb.", example:"Des Moines IA and Omaha NE have elevated atrazine from corn belt agricultural runoff." },
  { term:"Arsenic", full:"Arsenic Contamination", icon:"☠️", color:"#dc2626", def:"Naturally occurring metalloid found in groundwater especially in the West and Southwest. Long-term exposure linked to bladder, lung, and skin cancers. EPA limit 10 ppb.", example:"Phoenix AZ, Tucson AZ, and Albuquerque NM all have detected arsenic in some water sources." },
];
